### ISSUE TITLE
[Bug]: milvus crashes when insert data with 10 processes x10 threads 

### ISSUE THREAD

**Issue by WeiDong-Shi** [milvus-io/milvus#16079]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.0.1
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.0.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 8  Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz / 32G
- GPU: 
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:17:00.0 Off |                    0 |
| N/A   41C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 2070    Off  | 00000000:B3:00.0 Off |                  N/A |
| 41%   31C    P8     8W / 185W |    120MiB /  7981MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
- Others:
```

### Current Behavior

At present, I use 10 processes in the test. There are 10 threads in each process, and the number of data written by each thread is 10000. In the middle of the test, the mlivus node crashes.
We have also tested the smaller volume than this time and found the same problems, which will not emerge one by one for the time being.
[log.zip](https://github.com/milvus-io/milvus/files/8261340/log.zip).

### Expected Behavior

Node crash makes me unable to judge the stability of the service. I hope to find a solution.

### Steps To Reproduce

```markdown
Node crash makes me unable to judge the stability of the service. I hope to find a solution.
```

**Comment by Swd1993** [comment]
In addition, I execute 10 processes on two other servers, and there are not too many 5 processes on the server.

**Comment by yanliang567** [comment]
@Swd1993 I don't think standalone would take so much heavy insert(10*10*10000 entities at a time), I don't know the dim of your data, but I still suggest you retry with milvus cluster. Moreover, if you do want to insert with big throughput, i suggest you customize the pulsar service with more resource and replicas.

**Comment by xiaofan-luan** [comment]
> There are 10 threads in each process, and the number of data written by each thread is 10000. In the middle of the test, the mlivus node crashes.
> We have also tested the smaller volume than this time and found the same problems, which will not emerge one by one for the time being.

How much memory is there on your service?  I guess the crash is probably caused by OOM, you could check dmesg see if there is any message about OOM and also offer the log if there are any error message.

**Comment by xiaofan-luan** [comment]
In 2.1 we will introduce data import,  by then if would be much efficient to do bulk insertion

**Comment by Swd1993** [comment]
> @Swd1993我不认为standalone 会需要这么多的插入（一次10 _10_ 10000 个实体），我不知道你的数据有多暗，但我仍然建议你用milvus 集群重试。此外，如果您确实想以大吞吐量插入，我建议您使用更多资源和副本自定义 pulsar 服务。

I understand what you mean. I have also tested it in the cluster mode. There will be the same problem in the concurrent operation. Because my business needs continuous concurrent writes, I need to test our bottleneck to determine the hardware selection. At present, the node collapse will lead to the fault of our business. If the node does not collapse, I can also conduct direct supplementary recording in business, but if the node crashes, I can only choose a separate service to make up the missing data. Similarly, not all teams have the ability or resources to use k8s

**Comment by Swd1993** [comment]
> > 每个进程有10个线程，每个线程写入的数据数为10000。在测试中，mlivus节点崩溃。
> > 我们也测试了比这次更小的体积，也发现了同样的问题，暂时不会一一出现。
> 
> 您的服务有多少内存？我猜崩溃可能是OOM引起的，你可以检查dmesg看看是否有任何关于OOM的消息，如果有任何错误消息也提供日志。

My service memory is currently 32g. It is true that the memory will be full when writing. I don't know if there is not enough memory in the buffer to cause the node to crash. There is a great possibility of oom. I will continue to test and try to find the reason later.

**Comment by Swd1993** [comment]
> @Swd1993我不认为standalone 会需要这么多的插入（一次10 _10_ 10000 个实体），我不知道你的数据有多暗，但我仍然建议你用milvus 集群重试。此外，如果您确实想以大吞吐量插入，我建议您使用更多资源和副本自定义 pulsar 服务。

dim: 2048

**Comment by Swd1993** [comment]
> > 每个进程有10个线程，每个线程写入的数据数为10000。在测试中，mlivus节点崩溃。
> > 我们也测试了比这次更小的体积，也发现了同样的问题，暂时不会一一出现。
> 
> 您的服务有多少内存？我猜崩溃可能是OOM引起的，你可以检查dmesg看看是否有任何关于OOM的消息，如果有任何错误消息也提供日志。

Yes, by oom. Do we have any good suggestions for such a situation?

[三 3月 16 18:26:26 2022] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=774c57ae415df4ec3da306b02ede301f11923a89b838f6299433b2b0e69f1e5b,mems_allowed=0,global_oom,task_memcg=/docker/774c57ae415df4ec3da306b02ede301f11923a89b838f6299433b2b0e69f1e5b,task=milvus,pid=4942,uid=0
[三 3月 16 18:26:26 2022] Out of memory: Killed process 4942 (milvus) total-vm:37027072kB, anon-rss:21159080kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:60984kB oom_score_adj:0
[三 3月 16 18:26:27 2022] oom_reaper: reaped process 4942 (milvus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

[dmesg.log](https://github.com/milvus-io/milvus/files/8281008/dmesg.log)

**Comment by xiaofan-luan** [comment]
> > > 每个进程有10个线程，每个线程写入的数据数为10000。在测试中，mlivus节点崩溃。
> > > 我们也测试了比这次更小的体积，也发现了同样的问题，暂时不会一一出现。
> > 
> > 
> > 您的服务有多少内存？我猜崩溃可能是OOM引起的，你可以检查dmesg看看是否有任何关于OOM的消息，如果有任何错误消息也提供日志。
> 
> Yes, by oom. Do we have any good suggestions for such a situation?
> 
> [三 3月 16 18:26:26 2022] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=774c57ae415df4ec3da306b02ede301f11923a89b838f6299433b2b0e69f1e5b,mems_allowed=0,global_oom,task_memcg=/docker/774c57ae415df4ec3da306b02ede301f11923a89b838f6299433b2b0e69f1e5b,task=milvus,pid=4942,uid=0 [三 3月 16 18:26:26 2022] Out of memory: Killed process 4942 (milvus) total-vm:37027072kB, anon-rss:21159080kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:60984kB oom_score_adj:0 [三 3月 16 18:26:27 2022] oom_reaper: reaped process 4942 (milvus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
> 
> [dmesg.log](https://github.com/milvus-io/milvus/files/8281008/dmesg.log)

I would suggest to insert in 1000 batch with 10 concurrency and that should be working fine

**Comment by xiaofan-luan** [comment]
because 1w 2048 dim vectors will take around 150M memory

**Comment by WeiDong-Shi** [comment]
> 因为 1w 2048 个暗淡向量将占用大约 150M 内存

 can understand what you mean. In actual use, it may be written about 100 at a time, but under concurrent writing, may we have the same problem? At present, I can't start more processes, so I use more methods at a time. I want to know if our service can't write more at a time, Or is there any way to limit the number of concurrent Milvus

**Comment by WeiDong-Shi** [comment]
Finally, I hope that in the current situation, if our writing ability is not enough, will the interface reject the request instead of blocking the overflow of waiting memory. This is what I want to know. I need to know how to configure it.

**Comment by WeiDong-Shi** [comment]
> > > > 每个进程有10个线程，每个线程写入的数据数为10000。在测试中，mlivus节点崩溃。
> > > > 我们也测试了比这次更小的体积，也发现了同样的问题，暂时不会一一出现。
> > > 
> > > 
> > > 您的服务有多少内存？我猜崩溃可能是OOM引起的，你可以检查dmesg看看是否有任何关于OOM的消息，如果有任何错误消息也提供日志。
> > 
> > 
> > Yes, by oom. Do we have any good suggestions for such a situation?
> > [三 3月 16 18:26:26 2022] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=774c57ae415df4ec3da306b02ede301f11923a89b838f6299433b2b0e69f1e5b,mems_allowed=0,global_oom,task_memcg=/docker/774c57ae415df4ec3da306b02ede301f11923a89b838f6299433b2b0e69f1e5b,task=milvus,pid=4942,uid=0 [三 3月 16 18:26:26 2022] Out of memory: Killed process 4942 (milvus) total-vm:37027072kB, anon-rss:21159080kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:60984kB oom_score_adj:0 [三 3月 16 18:26:27 2022] oom_reaper: reaped process 4942 (milvus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
> > [dmesg.log](https://github.com/milvus-io/milvus/files/8281008/dmesg.log)
> 
> I would suggest to insert in 1000 batch with 10 concurrency and that should be working fine

At present, I am using the cluster mode. The writing mode is 5 processes. There are 5 threads in each process. The number of data written by each thread is 1000, and the vector dimension is 2048. The test found that the data node still crashes.

**Comment by WeiDong-Shi** [comment]
> 

Because the log cannot be uploaded, I sent it to you by email.

**Comment by WeiDong-Shi** [comment]
@xiaofan-luan 
Because the log cannot be uploaded, I sent it to you by email.
