### ISSUE TITLE
[Bug]: Load timeout after Milvus recovered from standalone pod kill chaos

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#17321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220601-63a31ccb
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus-2.1.0.dev66
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Load timeout when running test_e2e.py after standalone pod kill chaos

```
[2022-06-01T10:21:41.776Z] Traceback (most recent call last):

[2022-06-01T10:21:41.776Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 22, in inner_wrapper

[2022-06-01T10:21:41.776Z]     res = func(*args, **kwargs)

[2022-06-01T10:21:41.776Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 56, in api_request

[2022-06-01T10:21:41.776Z]     return func(*arg, **kwargs)

[2022-06-01T10:21:41.776Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/orm/collection.py", line 450, in load

[2022-06-01T10:21:41.776Z]     conn.load_collection(self._name, replica_number=replica_number, timeout=timeout, **kwargs)

[2022-06-01T10:21:41.776Z]   File "/usr/local/lib/python3.7/dist-packages/pymilvus/decorators.py", line 55, in handler

[2022-06-01T10:21:41.776Z]     raise MilvusException(Status.UNEXPECTED_ERROR, "rpc timeout")

[2022-06-01T10:21:41.776Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=rpc timeout)>

[2022-06-01T10:21:41.776Z]  (api_request.py:35)

[2022-06-01T10:21:41.776Z] [2022-06-01 10:21:39 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=rpc timeout)> (api_request.py:36)
```

### Expected Behavior

all test cases passed

### Milvus Log

server log
[artifacts-standalone-pod-kill-24-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/8813275/artifacts-standalone-pod-kill-24-server-logs.tar.gz)
 client log:
[artifacts-standalone-pod-kill-24-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/8813278/artifacts-standalone-pod-kill-24-pytest-logs.tar.gz)

### Anything else?

Probably the same problem as #17016

**Comment by zhuwenxing** [comment]
This failed again
https://github.com/milvus-io/milvus/runs/6695666895?check_suite_focus=true

It's strange, I thought it was for the same reason as querynode pod kill #17016 , but recently querynode pod kill doesn't have this problem

**Comment by yah01** [comment]
@zhuwenxing 
#17306 may fix this, could u verify it?

**Comment by zhuwenxing** [comment]
not reproduced in `master-20220602-48cf63a2`

**Comment by yah01** [comment]
@zhuwenxing 
The PR #17377 should fix this

**Comment by yah01** [comment]
@zhuwenxing 
Is this issue the same as #17016 ?

**Comment by zhuwenxing** [comment]
> @zhuwenxing Is this issue the same as #17016 ?

not sure about it. You can investigate it with the latest error log in https://github.com/milvus-io/milvus/issues/17321#issuecomment-1146977701.

Maybe they have some difference, because, from the current point of view, this issue still happened in version `master-20220602-48cf63a2`, but #17016 did not.

**Comment by yah01** [comment]
> > @zhuwenxing Is this issue the same as #17016 ?
> 
> not sure about it. You can investigate it with the latest error log in [#17321 (comment)](https://github.com/milvus-io/milvus/issues/17321#issuecomment-1146977701).
> 
> Maybe they have some difference, because, from the current point of view, this issue still happened in version `master-20220602-48cf63a2`, but #17016 did not.

OK, they both get stuck with LoadBalance, but for only querynode pod killed, #17306 fixes it. The entire system pod killed (this issue) should be fixed with #17377.

**Comment by zhuwenxing** [comment]
This issue happened again for both standalone and cluster

* standalone
    *  failed job: https://github.com/milvus-io/milvus/runs/6780408752?check_suite_focus=true
    * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285529
* all standalone
    * failed job: https://github.com/milvus-io/milvus/runs/6780408604?check_suite_focus=true
    * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285522
* all cluster
    * failed job: https://github.com/milvus-io/milvus/runs/6780408689?check_suite_focus=true
    * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285521

**Comment by zhuwenxing** [comment]
@yah01 
please help to take a look

**Comment by yah01** [comment]
> This issue happened again for both standalone and cluster
> 
> * standalone
>   
>   * failed job: https://github.com/milvus-io/milvus/runs/6780408752?check_suite_focus=true
>   * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285529
> * all standalone
>   
>   * failed job: https://github.com/milvus-io/milvus/runs/6780408604?check_suite_focus=true
>   * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285522
> * all cluster
>   
>   * failed job: https://github.com/milvus-io/milvus/runs/6780408689?check_suite_focus=true
>   * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285521

This is related to #17431, something wrong with the number of rows of segment

**Comment by xiaofan-luan** [comment]
@yah01 could this be related our latest load change? we might want to verify if data itself correct

**Comment by yah01** [comment]
> @yah01 could this be related our latest load change? we might want to verify if data itself correct

Recent changes to load:
- Load sealed segments concurrently: This may be related to this issue, it was merged on Jun 2, so I don't think it causes this.
- Avoid growing slices in InsertData: This only changes the cap of slice, not length.

**Comment by xige-16** [comment]
> This issue happened again for both standalone and cluster
> 
> * standalone
>   
>   * failed job: https://github.com/milvus-io/milvus/runs/6780408752?check_suite_focus=true
>   * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285529
> * all standalone
>   
>   * failed job: https://github.com/milvus-io/milvus/runs/6780408604?check_suite_focus=true
>   * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285522
> * all cluster
>   
>   * failed job: https://github.com/milvus-io/milvus/runs/6780408689?check_suite_focus=true
>   * log: https://github.com/milvus-io/milvus/suites/6832210137/artifacts/263285521

in cluster log, segmentLoad info of segment 433750697270837249 has segment(433750697254322177)'s indexInfo, it is wrong

```
[2022/06/07 18:53:30.911 +00:00] [INFO] [task.go:2034] ["loadBalanceTask: add a childTask"] ["task type"=LoadSegments] [task="base:<msg_type:LoadSegments sourceID:15 > dst_nodeID:14 
infos:<segmentID:433750697270837249 partitionID:433750697087536450 collectionID:433750697087536449 
binlog_paths:<binlogs:<entries_num:1497  log_path:\"file/insert_log/433750697087536449/433750697087536450/433750697270837249/0/433750697939304453\" log_size:4186 > > 
binlog_paths:<fieldID:1 binlogs:<entries_num:1497 log_path:\"file/insert_log/433750697087536449/433750697087536450/433750697270837249/1/433750697939304454\" log_size:543 > > 
binlog_paths:<fieldID:100 binlogs:<entries_num:1497 log_path:\"file/insert_log/433750697087536449/433750697087536450/433750697270837249/100/433750697939304449\" log_size:4864 > > 
binlog_paths:<fieldID:101 binlogs:<entries_num:1497 log_path:\"file/insert_log/433750697087536449/433750697087536450/433750697270837249/101/433750697939304450\" log_size:6298 > > 
binlog_paths:<fieldID:102 binlogs:<entries_num:1497 log_path:\"file/insert_log/433750697087536449/433750697087536450/433750697270837249/102/433750697939304451\" log_size:5210 > > 
binlog_paths:<fieldID:103 binlogs:<entries_num:1497 log_path:\"file/insert_log/433750697087536449/433750697087536450/433750697270837249/103/433750697939304452\" log_size:691133 > > num_of_rows:1497 
statslogs:<fieldID:100 binlogs:<log_path:\"file/stats_log/433750697087536449/433750697087536450/433750697270837249/100/433750697939304449\" log_size:183905 > > 
deltalogs:<> 

index_infos:<fieldID:103 enable_index:true index_name:\"_default_idx\" indexID:433750698057793537 buildID:433750698062512130 
index_params:<key:\"index_type\" value:\"IVF_SQ8\" > index_params:<key:\"metric_type\" value:\"L2\" > index_params:<key:\"params\" value:\"{\\\"nlist\\\": 64}\" > 
index_file_paths:\"file/index_files/433750698062512130/1/433750697087536450/433750697254322177/indexParams\" 
index_file_paths:\"file/index_files/433750698062512130/1/433750697087536450/433750697254322177/IVF\" index_size:217694 >

index_infos:<fieldID:103 enable_index:true index_name:\"_default_idx\" indexID:433750698057793537 buildID:433750698075095042 
index_params:<key:\"index_type\" value:\"IVF_SQ8\" > index_params:<key:\"metric_type\" value:\"L2\" > index_params:<key:\"params\" value:\"{\\\"nlist\\\": 64}\" > 
index_file_paths:\"file/index_files/433750698075095042/1/433750697087536450/433750697270837249/indexParams\" 
index_file_paths:\"file/index_files/433750698075095042/1/433750697087536450/433750697270837249/IVF\" index_size:216765 > segment_size:421771 insert_channel:\"by-dev-rootcoord-dml_1_433750697087536449v1\" > 
```

**Comment by xige-16** [comment]
same reason with https://github.com/milvus-io/milvus/issues/17431#issuecomment-1150714797

**Comment by yah01** [comment]
@zhuwenxing 
Could u verify this, as #17042 has been reverted?

**Comment by zhuwenxing** [comment]
verified and passed in version ` master-20220610-a5b008ac`
![image](https://user-images.githubusercontent.com/12268675/173015411-c97ae551-c964-4c66-b3eb-114ad078bf86.png)

**Comment by zhuwenxing** [comment]
Not reproduced yet,so close it
