### ISSUE TITLE
[Bug]: Failed to load in a 100 million vector set

### ISSUE THREAD

**Issue by lvmnn** [milvus-io/milvus#18220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: milvus 2.1    branch
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: 24 * 8c 48g
- GPU: 
- Others:
```

### Current Behavior

Vector set: 100 million

Index: ivf_flat

dim: 512

replications: 1

When the query node size is 24 x 8c/32g, the query node displays oom or fails the health check

When the query node size is 24 x 8c/48g, the load fails。

According to the Query Node log, both the raw vector and the index file are loaded

### Expected Behavior

Load succeeded. Only index data is loaded

### Milvus Log

[milvus-log.tar.gz](https://github.com/milvus-io/milvus/files/9081349/milvus-log.tar.gz)

**Comment by xiaofan-luan** [comment]
/assign @yah01 could you please help on verifying it
thanks

**Comment by yah01** [comment]
According to the logs, the QueryNode reports NoSuchKey error when loading segment from MinioChunkManager, it seems the binlog paths are not correct.

**Comment by jiaoew1991** [comment]
Hi @lvmnn could help us to check the folder  `index_files/434482881431601156/1/434444451783114754/434445985561444353/` on your storage is exist ? 
from the logs we find out all of the QueryNodes try to load the index files in this folder but failed.

**Comment by jiaoew1991** [comment]
It's quite similar with https://github.com/milvus-io/milvus/issues/18158, the garbage cleaner policy had a bug maybe delete index files which being used. 

#18158 was already fixed by https://github.com/milvus-io/milvus/commit/26b302775286f77552ddf1b06cef4dc0dcf42e34 which contained in the version https://github.com/milvus-io/milvus/commit/8cc6e9314c017168f27dbee2abd802e2d5c51096 which you are using. 

@lvmnn Could you help us to confirm which Milvus version was used to create the collection? Is it created by an older version Milvus?

**Comment by lvmnn** [comment]
milvusdb/milvus-dev:2.1.0-20220708-a6692a41

@jiaoew1991 We used this mirror image at that time, and this error did not occur again in the subsequent test of the new version👍

**Comment by nicolasf** [comment]
Seems like I have the same problem using Milvus 2.1.1.

Out of 3 query nodes, 2 seemed to finish loading a 117M collection correctly, and the last node spent quite some time trying to load some specific data and failed, until it gave up and the whole index was discarded from memory on the cluster.

Here's part of the log:

`[2022/08/23 00:52:08.476 +00:00] [INFO] [querynode/segment_loader.go:375] ["load field binlogs done for sealed segment"] [collection=435427637596782593] [segment=435442073893076996] [len(field)=3] [segmentType=Sealed]
[2022/08/23 00:52:08.503 +00:00] [ERROR] [querynode/segment_loader.go:171] ["load segment failed when load data into memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435448801805729793] [segmentType=Sealed] [error=NoSuchKey] [stack="github.com/milvus-io/milvus/internal/querynode.(*segmentLoader).LoadSegment.func3\n\t/go/src/github.com/milvus-io/milvus/internal/querynode/segment_loader.go:171\ngithub.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:83"]
[2022/08/23 00:52:08.503 +00:00] [ERROR] [funcutil/parallel.go:85] [loadSegmentFunc] [error=NoSuchKey] [idx=9] [stack="github.com/milvus-io/milvus/internal/util/funcutil.ProcessFuncParallel.func3\n\t/go/src/github.com/milvus-io/milvus/internal/util/funcutil/parallel.go:85"]
[2022/08/23 00:52:08.708 +00:00] [INFO] [querynode/segment.go:847] ["load deleted record done"] ["row count"=180226] [segmentID=435428009815048195] [segmentType=Sealed]
[2022/08/23 00:52:08.845 +00:00] [INFO] [querynode/segment.go:847] ["load deleted record done"] ["row count"=53996] [segmentID=435442073893076996] [segmentType=Sealed]
[2022/08/23 00:52:08.893 +00:00] [INFO] [querynode/segment.go:847] ["load deleted record done"] ["row count"=70747] [segmentID=435439969584545795] [segmentType=Sealed]
[2022/08/23 00:52:08.907 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435442073893076996] [segmentType=Sealed]
[2022/08/23 00:52:08.915 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435431344142811139] [segmentType=Sealed]
[2022/08/23 00:52:08.922 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435429916113371144] [segmentType=Sealed]
[2022/08/23 00:52:08.929 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435439969584545795] [segmentType=Sealed]
[2022/08/23 00:52:08.937 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435429416571502595] [segmentType=Sealed]
[2022/08/23 00:52:08.945 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435428009815048195] [segmentType=Sealed]
[2022/08/23 00:52:08.950 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435448801805729793] [segmentType=Sealed]
[2022/08/23 00:52:08.957 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435438565109006339] [segmentType=Sealed]
[2022/08/23 00:52:08.965 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435448541155950595] [segmentType=Sealed]
[2022/08/23 00:52:08.972 +00:00] [INFO] [querynode/segment.go:237] ["delete segment from memory"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435442491226587139] [segmentType=Sealed]
[2022/08/23 00:52:08.977 +00:00] [WARN] [querynode/task.go:523] ["failed to load segment"] [collectionID=435427637596782593] [replicaID=435415565186629819] [error=NoSuchKey]
[2022/08/23 00:52:08.977 +00:00] [WARN] [querynode/task_scheduler.go:112] [NoSuchKey]
[2022/08/23 00:52:08.977 +00:00] [INFO] [querynode/task.go:489] ["LoadSegmentTask PreExecute start"] [msgID=435475057074070959]
[2022/08/23 00:52:08.977 +00:00] [INFO] [querynode/task.go:515] ["LoadSegmentTask PreExecute done"] [msgID=435475057074070959]
[2022/08/23 00:52:08.977 +00:00] [INFO] [querynode/task.go:520] ["LoadSegmentTask Execute start"] [msgID=435475057074070959]
[2022/08/23 00:52:08.977 +00:00] [INFO] [querynode/segment_loader.go:92] ["segmentLoader start loading..."] [collectionID=435427637596782593] [segmentNum=10] [segmentType=Sealed]
[2022/08/23 00:52:08.977 +00:00] [WARN] [querynode/impl.go:184] [NoSuchKey]
[2022/08/23 00:52:08.977 +00:00] [INFO] [querynode/segment.go:199] ["create segment"] [collectionID=435427637596782593] [partitionID=435427637596782594] [segmentID=435427822264385539] [segmentType=Sealed]
`

Version 2.1.1 apparently has a few garbageCollector fixes commited, so I'm wondering if this is a different problem or a regression.

**Comment by yanliang567** [comment]
@nicolasf thank you for updates. did you(sdk) get any error when you try to load the collection? if yes, please open a new issue and refer this [script](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

**Comment by yhmo** [comment]
User still encounter this error: https://app.slack.com/client/TM98LD8DQ/search/search-eyJkIjoiTm9TdWNoS2V5IiwicSI6IlVOS0xQUFo0NiIsInIiOiJOb1N1Y2hLZXkifQ==/thread/CMNHUC371-1664392361.355889?cdn_fallback=2

**Comment by Roger-Z** [comment]
> milvusdb/milvus-dev:2.1.0-20220708-a6692a41
> 
> @jiaoew1991 We used this image at that time, and this error did not occur again in the subsequent test of the new version👍
 @lvmnn we encounter the same issue in v2.0.2, and after upgrade to 2.1.4, the issue still exists. Would you please let me know what you have done to fix this problem?
