### ISSUE TITLE
[Bug]: There will be more than one task that state is started when bulk load when there is only one datanode

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#19563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220928-adeaac4f
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus==2.2.0.dev36
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

![HjsHFhCb8D](https://user-images.githubusercontent.com/12268675/193011522-9b11c370-b5ad-41ba-b0ea-16bb3ee0571f.jpg)

### Milvus Log

[test-milvus-bulk-load-09-29-17-45 .zip](https://github.com/milvus-io/milvus/files/9673436/test-milvus-bulk-load-09-29-17-45.zip)

**Comment by soothing-rain** [comment]
Should be fixed by https://github.com/milvus-io/milvus/pull/19561

**Comment by zhuwenxing** [comment]
pymilvus==2.2.0.dev38
Milvus version: master-20221008-5b4038e9

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/bulk_load_test/detail/bulk_load_test/19/pipeline

![image](https://user-images.githubusercontent.com/12268675/194695688-79b0fbbd-d6f2-4221-b260-6116fdb04e8b.png)

log:

[artifacts-bulk-load-test-19-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9738681/artifacts-bulk-load-test-19-pytest-logs.1.tar.gz)

[artifacts-bulk-load-test-19-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9738682/artifacts-bulk-load-test-19-server-logs.2.tar.gz)

**Comment by soothing-rain** [comment]
> pymilvus==2.2.0.dev38 Milvus version: master-20221008-5b4038e9
> 
> failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/bulk_load_test/detail/bulk_load_test/19/pipeline
> 
> ![image](https://user-images.githubusercontent.com/12268675/194695688-79b0fbbd-d6f2-4221-b260-6116fdb04e8b.png)
> 
> log:
> 
> [artifacts-bulk-load-test-19-pytest-logs (1).tar.gz](https://github.com/milvus-io/milvus/files/9738681/artifacts-bulk-load-test-19-pytest-logs.1.tar.gz)
> 
> [artifacts-bulk-load-test-19-server-logs (2).tar.gz](https://github.com/milvus-io/milvus/files/9738682/artifacts-bulk-load-test-19-server-logs.2.tar.gz)

But there are two DataNode services right?

**Comment by zhuwenxing** [comment]
> But there are two DataNode services right?
Yes, so it is as expected!

**Comment by zhuwenxing** [comment]
Milvus version: master-20221008-7e620a7a

It still happened in the datanode pod killchaos test
log:
[artifacts-bulk-load-test-6-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/9739068/artifacts-bulk-load-test-6-server-logs.tar.gz)
[artifacts-bulk-load-test-6-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/9739069/artifacts-bulk-load-test-6-pytest-logs.tar.gz)

before chaos, it works well, there is only one working task when datanode number is 1.
![image](https://user-images.githubusercontent.com/12268675/194704987-0d6aef4b-0f74-4af9-a786-4a4584fccfdd.png)

during chaos, it becomes abnormal.
![image](https://user-images.githubusercontent.com/12268675/194705024-a6a3cfd1-b4d9-4933-aa24-1a5c04012dfc.png)

after chaos, the working tasks number is still wrong
![image](https://user-images.githubusercontent.com/12268675/194705102-7ca82bac-877e-47d1-8956-356536368282.png)

**Comment by soothing-rain** [comment]
OK this might make sense in chaos testing.

If a DataNode gets killed while working on a bulk load task, the state of that task will stay in `STARTED` and will eventually be removed when expired. In other words, these are "dead" bulk load tasks in `STARTED` states.

Also these "dead" tasks will not impact future bulk load tasks, as new tasks will be assigned to new DataNodes.

**Comment by zhuwenxing** [comment]
Though they are "dead" `STARTED` tasks, it would be better to clean them, otherwise, it will make the user confused.

So I think it is still a bug that needs to fix, but the priority is not that high.

**Comment by soothing-rain** [comment]
> Though they are "dead" `STARTED` tasks, it would be better to clean them, otherwise, it will make the user confused.
> 
> So I think it is still a bug that needs to fix, but the priority is not that high.

Sure I created a new issue for this one:
https://github.com/milvus-io/milvus/issues/19777

We can close 19563 for now.

/assign @zhuwenxing
