### ISSUE TITLE
[Bug]: fail to create a collection alias with the same name of a dropped collection

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/milvus#25541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230712-dbf01308
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
```

### Current Behavior

fail to create alias if the alias name is the same as a dropped collection
[2023-07-12 17:53:37,904 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=cannot create alias, collection already exists with same name: aa_lS0Vm1jk)> (api_request.py:40)

### Expected Behavior

create alias successfully

### Steps To Reproduce

```markdown
self._connect()
        a_name = cf.gen_unique_str("aa")
        b_name = cf.gen_unique_str("bb")
        collection_a = self.init_collection_wrap(name=a_name, schema=default_schema,
                                                 check_task=CheckTasks.check_collection_property,
                                                 check_items={exp_name: a_name, exp_schema: default_schema})
        collection_b = self.init_collection_wrap(name=b_name, schema=default_schema,
                                                 check_task=CheckTasks.check_collection_property,
                                                 check_items={exp_name: b_name, exp_schema: default_schema})
        # drop the collection a
        self.utility_wrap.drop_collection(a_name)
        assert self.utility_wrap.has_collection(a_name)[0] is False
        b_alias, _ = self.utility_wrap.list_aliases(b_name)
        # create alias with the name of collection a
        self.utility_wrap.create_alias(b_name, a_name)
        # assert create alias succ
        b_alias, _ = self.utility_wrap.list_aliases(b_name)
        assert len(b_alias) == 1
```

**Comment by wayblink** [comment]
Seems fixed in #25616. I verify this in newest master. Please verify this @yanliang567

**Comment by yanliang567** [comment]
@NicoYuan1986 could you please help to verify this issue and add a test to ci accordinlgy?

/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
Fixed. 
![image](https://github.com/milvus-io/milvus/assets/109071306/0b59ab07-8b71-4832-ae01-72def13e4290)

milvus: master-20230728-c2693ea2
pymilvus: 2.4.0.dev111

**Comment by NicoYuan1986** [comment]
Not fixed. I found it failed on 2.2 branch too.  @yanliang567 
```
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['bb_dxFCXPnQ', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VARCH......, kwargs: {'shards_num': 2, 'consistency_level': 'Strong'} (api_request.py:56)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_response) : <Collection>:
-------------
<name>: bb_dxFCXPnQ
<description>: 
<schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'na......  (api_request.py:31)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_request)  : [drop_collection] args: ['aa_Gs67Jdze', None, 'default'], kwargs: {} (api_request.py:56)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_response) : None  (api_request.py:31)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_request)  : [has_collection] args: ['aa_Gs67Jdze', 'default'], kwargs: {} (api_request.py:56)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_response) : False  (api_request.py:31)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_request)  : [list_aliases] args: ['bb_dxFCXPnQ', 20, 'default'], kwargs: {} (api_request.py:56)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_response) : []  (api_request.py:31)
[2023-08-01 19:07:31 - DEBUG - ci_test]: (api_request)  : [create_alias] args: ['bb_dxFCXPnQ', 'aa_Gs67Jdze', 20, 'default'], kwargs: {} (api_request.py:56)
[2023-08-01 19:07:31 - ERROR - pymilvus.decorators]: RPC error: [create_alias], <MilvusException: (code=1, message=cannot create alias, collection already exists with same name: aa_Gs67Jdze)>, <Time:{'RPC start': '2023-08-01 19:07:31.507432', 'RPC error': '2023-08-01 19:07:31.522830'}> (decorators.py:126)
[2023-08-01 19:07:31 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/2.2/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/2.2/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/orm/utility.py", line 672, in create_alias
    return _get_connection(using).create_alias(collection_name, alias, timeout=timeout)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 127, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 123, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 162, in handler
    return func(self, *args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 102, in handler
    raise e from e
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/decorators.py", line 68, in handler
    return func(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus/lib/python3.10/site-packages/pymilvus/client/grpc_handler.py", line 691, in create_alias
    raise MilvusException(response.error_code, response.reason)
pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=cannot create alias, collection already exists with same name: aa_Gs67Jdze)>
 (api_request.py:39)
[2023-08-01 19:07:31 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=cannot create alias, collection already exists with same name: aa_Gs67Jdze)> (api_request.py:40)
```

**Comment by yanliang567** [comment]
this issue will not be fixed in 2.2.0 branch.
