### ISSUE TITLE
[Bug]: Why can't I delete entities, and how to determine the root cause

### ISSUE THREAD

**Issue by baosince** [milvus-io/milvus#28548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.2.10 
- Deployment mode(standalone or cluster): kubernetes standalone
- MQ type(rocksmq, pulsar or kafka): none
- SDK version(e.g. pymilvus v2.0.0rc2): java 2.2.9
- OS(Ubuntu or CentOS): 
- CPU/Memory: none
- GPU: none
- Others:
```

### Current Behavior

My deployment mode is kubernetes standalone.
Java sdk returned true after I called my api to delete the entities, but it didn't actually work. 
Milvus didn't not print deletion related logs.

The same api and code works well with the milvus deployed in docker-compose.

### Milvus Log

NAME                                               READY   STATUS    RESTARTS   AGE
milvus-standalone-etcd-0                           1/1     Running   0          45m
milvus-standalone-minio-9b7855d77-69q87            1/1     Running   0          45m
milvus-standalone-standalone-7c6fff47bc-crn4s      1/1     Running   0          30m

[2023/11/17 11:20:50.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:50.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:51.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:51.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:52.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:52.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:53.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:53.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:54.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:54.066 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:55.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:55.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:56.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:56.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:57.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:57.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:58.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:58.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:20:59.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:20:59.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:00.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:00.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:01.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:01.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:02.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:02.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:03.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:03.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:03.257 +00:00] [INFO] [rootcoord/import_manager.go:177] ["(in cleanupLoop) trying to expire old tasks from memory and Etcd"]
[2023/11/17 11:21:03.258 +00:00] [INFO] [rootcoord/import_manager.go:180] ["(in cleanupLoop) start removing bad import segments"]
[2023/11/17 11:21:03.258 +00:00] [INFO] [rootcoord/import_manager.go:182] ["(in cleanupLoop) start cleaning hanging busy DataNode"]
[2023/11/17 11:21:03.463 +00:00] [INFO] [indexcoord/index_coord.go:890] ["IndexCoord DescribeIndex"] [collectionID=443795323898595897] [indexName=]
[2023/11/17 11:21:03.463 +00:00] [INFO] [datacoord/services.go:888] ["received get flushed segments request"] [collectionID=443795323898595897] [partitionID=-1]
[2023/11/17 11:21:03.463 +00:00] [INFO] [datacoord/services.go:786] ["get recovery info request received"] [collectionID=443795323898595897] [partitionIDs="[]"]
[2023/11/17 11:21:03.464 +00:00] [INFO] [rootcoord/root_coord.go:1151] ["received request to describe collection"] [traceID=a2cb9a84b60cb41] ["collection name"=] [dbName=] [id=443795323898595897] [m
sgID=0] [ts=18446744073709551615] [allowUnavailable=true]
[2023/11/17 11:21:03.464 +00:00] [INFO] [rootcoord/root_coord.go:1184] ["done to describe collection"] [traceID=a2cb9a84b60cb41] ["collection name"=] [dbName=] [id=443795323898595897] [msgID=0] [ts=
18446744073709551615] [allowUnavailable=true] [collection_id=443795323898595897]
[2023/11/17 11:21:03.464 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=443795323898595897] [channel=by-dev-rootcoord-dml_0_443795323898595897v0] [numOfSegments=2]
[2023/11/17 11:21:03.464 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_0_443795323898595897v0] [posTs=44570246407
9921153] [posTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:03.464 +00:00] [INFO] [datacoord/services.go:822] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=443795323898595897] [partitionIDs="[]"] [channelInfo="collection
ID:443795323898595897 channelName:\"by-dev-rootcoord-dml_0_443795323898595897v0\" seek_position:<channel_name:\"by-dev-rootcoord-dml_0_443795323898595897v0\" msgID:\"\\242\\024\\344\\344\\372s/\\006
\" msgGroup:\"by-dev-dataNode-134-by-dev-rootcoord-dml_0_443795323898595897v0\" timestamp:445702464079921153 > unflushedSegmentIds:445653408876123271 flushedSegmentIds:445653408875661684 "]
[2023/11/17 11:21:03.464 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=443795323898595897] [channel=by-dev-rootcoord-dml_1_443795323898595897v1] [numOfSegments=2]
[2023/11/17 11:21:03.464 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_1_443795323898595897v1] [posTs=44570246407
9921153] [posTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:03.464 +00:00] [INFO] [datacoord/services.go:822] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=443795323898595897] [partitionIDs="[]"] [channelInfo="collection
ID:443795323898595897 channelName:\"by-dev-rootcoord-dml_1_443795323898595897v1\" seek_position:<channel_name:\"by-dev-rootcoord-dml_1_443795323898595897v1\" msgID:\"\\241\\024\\344\\344\\372s/\\006
\" msgGroup:\"by-dev-dataNode-134-by-dev-rootcoord-dml_1_443795323898595897v1\" timestamp:445702464079921153 > unflushedSegmentIds:445653408876123270 flushedSegmentIds:445653408875661681 "]
[2023/11/17 11:21:03.465 +00:00] [INFO] [indexcoord/index_coord.go:611] ["IndexCoord completeIndexInfo"] [collID=443795323898595897] [indexName=_default_idx_101]
[2023/11/17 11:21:03.465 +00:00] [INFO] [indexcoord/index_coord.go:632] ["IndexCoord completeIndexInfo success"] [collID=443795323898595897] [totalRows=4641] [indexRows=4641] [state=Finished] [failR
eason=]
[2023/11/17 11:21:03.465 +00:00] [INFO] [indexcoord/index_coord.go:951] ["IndexCoord describe index success"] [collectionID=443795323898595897] [indexID=443795323898596389] ["total rows"=4641] ["ind
exed rows"=4641] ["pending index rows"=0] ["index state"=Finished] [segments="[]"]
[2023/11/17 11:21:03.465 +00:00] [INFO] [indexcoord/index_coord.go:890] ["IndexCoord DescribeIndex"] [collectionID=443795323898595897] [indexName=]
[2023/11/17 11:21:03.465 +00:00] [INFO] [datacoord/services.go:888] ["received get flushed segments request"] [collectionID=443795323898595897] [partitionID=-1]
[2023/11/17 11:21:03.466 +00:00] [INFO] [datacoord/services.go:786] ["get recovery info request received"] [collectionID=443795323898595897] [partitionIDs="[]"]
[2023/11/17 11:21:03.466 +00:00] [INFO] [rootcoord/root_coord.go:1151] ["received request to describe collection"] [traceID=115349f5d3a3a07b] ["collection name"=] [dbName=] [id=443795323898595897] [
msgID=0] [ts=18446744073709551615] [allowUnavailable=true]
[2023/11/17 11:21:03.466 +00:00] [INFO] [rootcoord/root_coord.go:1184] ["done to describe collection"] [traceID=115349f5d3a3a07b] ["collection name"=] [dbName=] [id=443795323898595897] [msgID=0] [ts
=18446744073709551615] [allowUnavailable=true] [collection_id=443795323898595897]
[2023/11/17 11:21:03.466 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=443795323898595897] [channel=by-dev-rootcoord-dml_0_443795323898595897v0] [numOfSegments=2]
[2023/11/17 11:21:03.466 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_0_443795323898595897v0] [posTs=44570246407
9921153] [posTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:03.466 +00:00] [INFO] [datacoord/services.go:822] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=443795323898595897] [partitionIDs="[]"] [channelInfo="collection
ID:443795323898595897 channelName:\"by-dev-rootcoord-dml_0_443795323898595897v0\" seek_position:<channel_name:\"by-dev-rootcoord-dml_0_443795323898595897v0\" msgID:\"\\242\\024\\344\\344\\372s/\\006
\" msgGroup:\"by-dev-dataNode-134-by-dev-rootcoord-dml_0_443795323898595897v0\" timestamp:445702464079921153 > unflushedSegmentIds:445653408876123271 flushedSegmentIds:445653408875661684 "]
[2023/11/17 11:21:03.466 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=443795323898595897] [channel=by-dev-rootcoord-dml_1_443795323898595897v1] [numOfSegments=2]
[2023/11/17 11:21:03.466 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_1_443795323898595897v1] [posTs=44570246407
9921153] [posTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:03.466 +00:00] [INFO] [datacoord/services.go:822] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=443795323898595897] [partitionIDs="[]"] [channelInfo="collection
ID:443795323898595897 channelName:\"by-dev-rootcoord-dml_1_443795323898595897v1\" seek_position:<channel_name:\"by-dev-rootcoord-dml_1_443795323898595897v1\" msgID:\"\\241\\024\\344\\344\\372s/\\006
\" msgGroup:\"by-dev-dataNode-134-by-dev-rootcoord-dml_1_443795323898595897v1\" timestamp:445702464079921153 > unflushedSegmentIds:445653408876123270 flushedSegmentIds:445653408875661681 "]
[2023/11/17 11:21:03.467 +00:00] [INFO] [indexcoord/index_coord.go:611] ["IndexCoord completeIndexInfo"] [collID=443795323898595897] [indexName=_default_idx_101]
[2023/11/17 11:21:03.467 +00:00] [INFO] [indexcoord/index_coord.go:632] ["IndexCoord completeIndexInfo success"] [collID=443795323898595897] [totalRows=4641] [indexRows=4641] [state=Finished] [failR
eason=]
[2023/11/17 11:21:03.467 +00:00] [INFO] [indexcoord/index_coord.go:951] ["IndexCoord describe index success"] [collectionID=443795323898595897] [indexID=443795323898596389] ["total rows"=4641] ["ind
exed rows"=4641] ["pending index rows"=0] ["index state"=Finished] [segments="[]"]
[2023/11/17 11:21:03.694 +00:00] [INFO] [datacoord/services.go:888] ["received get flushed segments request"] [collectionID=443795323898595897] [partitionID=-1]
[2023/11/17 11:21:03.921 +00:00] [INFO] [datanode/flow_graph_time_tick_node.go:115] ["UpdateChannelCheckpoint success"] [channel=by-dev-rootcoord-dml_1_443795323898595897v1] [cpTs=445702464079921153
] [cpTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:03.921 +00:00] [INFO] [datanode/flow_graph_time_tick_node.go:115] ["UpdateChannelCheckpoint success"] [channel=by-dev-rootcoord-dml_0_443795323898595897v0] [cpTs=445702464079921153
] [cpTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:04.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:04.067 +00:00] [INFO] [observers/target_observer.go:262] ["observer trigger update current target"] [collectionID=443795323898595897]
[2023/11/17 11:21:04.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:04.067 +00:00] [INFO] [observers/target_observer.go:213] ["observer trigger update next target"] [collectionID=443795323898595897]
[2023/11/17 11:21:04.067 +00:00] [INFO] [datacoord/services.go:786] ["get recovery info request received"] [collectionID=443795323898595897] [partitionIDs="[443795323898596473,443795323898596476,443
795323898596479]"]
[2023/11/17 11:21:04.068 +00:00] [INFO] [rootcoord/root_coord.go:1151] ["received request to describe collection"] [traceID=7cf5cd8092e7941f] ["collection name"=] [dbName=] [id=443795323898595897] [
msgID=0] [ts=18446744073709551615] [allowUnavailable=true]
[2023/11/17 11:21:04.068 +00:00] [INFO] [rootcoord/root_coord.go:1184] ["done to describe collection"] [traceID=7cf5cd8092e7941f] ["collection name"=] [dbName=] [id=443795323898595897] [msgID=0] [ts
=18446744073709551615] [allowUnavailable=true] [collection_id=443795323898595897]
[2023/11/17 11:21:04.068 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=443795323898595897] [channel=by-dev-rootcoord-dml_0_443795323898595897v0] [numOfSegments=2]
[2023/11/17 11:21:04.068 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_0_443795323898595897v0] [posTs=44570246407
9921153] [posTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:04.068 +00:00] [INFO] [datacoord/services.go:822] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=443795323898595897] [partitionIDs="[443795323898596473,443795323
898596476,443795323898596479]"] [channelInfo="collectionID:443795323898595897 channelName:\"by-dev-rootcoord-dml_0_443795323898595897v0\" seek_position:<channel_name:\"by-dev-rootcoord-dml_0_4437953
23898595897v0\" msgID:\"\\242\\024\\344\\344\\372s/\\006\" msgGroup:\"by-dev-dataNode-134-by-dev-rootcoord-dml_0_443795323898595897v0\" timestamp:445702464079921153 > unflushedSegmentIds:44565340887
6123271 flushedSegmentIds:445653408875661684 "]
[2023/11/17 11:21:04.069 +00:00] [INFO] [datacoord/handler.go:119] [GetQueryVChanPositions] [collectionID=443795323898595897] [channel=by-dev-rootcoord-dml_1_443795323898595897v1] [numOfSegments=2]
[2023/11/17 11:21:04.069 +00:00] [INFO] [datacoord/handler.go:288] ["channel seek position set from channel checkpoint meta"] [channel=by-dev-rootcoord-dml_1_443795323898595897v1] [posTs=44570246407
9921153] [posTime=2023/11/17 11:19:31.008 +00:00]
[2023/11/17 11:21:04.069 +00:00] [INFO] [datacoord/services.go:822] ["datacoord append channelInfo in GetRecoveryInfo"] [collectionID=443795323898595897] [partitionIDs="[443795323898596473,443795323
898596476,443795323898596479]"] [channelInfo="collectionID:443795323898595897 channelName:\"by-dev-rootcoord-dml_1_443795323898595897v1\" seek_position:<channel_name:\"by-dev-rootcoord-dml_1_4437953
23898595897v1\" msgID:\"\\241\\024\\344\\344\\372s/\\006\" msgGroup:\"by-dev-dataNode-134-by-dev-rootcoord-dml_1_443795323898595897v1\" timestamp:445702464079921153 > unflushedSegmentIds:44565340887
6123270 flushedSegmentIds:445653408875661681 "]
[2023/11/17 11:21:04.321 +00:00] [INFO] [proxy/meta_cache.go:869] ["expire all shard leader cache"] [database=default] [collections="[embedding015]"]
[2023/11/17 11:21:05.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:05.066 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:06.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:06.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:07.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:07.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:08.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:08.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:09.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:09.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:10.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:10.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:11.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:11.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:12.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:12.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:13.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:13.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:13.303 +00:00] [INFO] [querycoordv2/services.go:144] ["show partitions request received"] [msgID=0] [collectionID=443795323898595897] [partitions="[443795323898596473,4437953238985
96476,443795323898596479]"]
[2023/11/17 11:21:13.315 +00:00] [INFO] [proxy/meta_cache.go:751] ["no shard cache for collection, try to get shard leaders from QueryCoord"] [collectionName=embedding015]
[2023/11/17 11:21:13.315 +00:00] [INFO] [querycoordv2/services.go:871] ["get shard leaders request received"] [msgID=0] [collectionID=443795323898595897]
[2023/11/17 11:21:13.533 +00:00] [INFO] [querycoordv2/services.go:144] ["show partitions request received"] [msgID=0] [collectionID=443795323898595897] [partitions="[443795323898596473,4437953238985
96476,443795323898596479]"]
[2023/11/17 11:21:13.544 +00:00] [INFO] [proxy/impl.go:791] ["DescribeCollection received"] [traceID=590678456d5a04fd] [role=proxy] [db=default] [collection=embedding015]
[2023/11/17 11:21:13.544 +00:00] [INFO] [proxy/impl.go:815] ["DescribeCollection enqueued"] [traceID=590678456d5a04fd] [role=proxy] [MsgID=445702490949419010] [BeginTS=445702490949419010] [EndTS=445
702490949419010] [db=default] [collection=embedding015]
[2023/11/17 11:21:13.544 +00:00] [INFO] [rootcoord/root_coord.go:1151] ["received request to describe collection"] [traceID=590678456d5a04fd] ["collection name"=embedding015] [dbName=default] [id=0]
 [msgID=445702490949419010] [ts=18446744073709551615] [allowUnavailable=false]
[2023/11/17 11:21:13.545 +00:00] [INFO] [rootcoord/root_coord.go:1184] ["done to describe collection"] [traceID=590678456d5a04fd] ["collection name"=embedding015] [dbName=default] [id=0] [msgID=4457
02490949419010] [ts=18446744073709551615] [allowUnavailable=false] [collection_id=443795323898595897]
[2023/11/17 11:21:13.545 +00:00] [INFO] [proxy/impl.go:846] ["DescribeCollection done"] [traceID=590678456d5a04fd] [role=proxy] [MsgID=445702490949419010] [BeginTS=445702490949419010] [EndTS=4457024
90949419010] [db=default] [collection=embedding015]
[2023/11/17 11:21:14.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:14.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:14.522 +00:00] [INFO] [gc/gc_tuner.go:84] ["GC Tune done"] ["previous GOGC"=200] ["heapuse "=150] ["total memory"=670] ["next GC"=153] ["new GOGC"=200] [gc-pause=383.884µs] [gc-pau
se-end=1700220074520988831]
[2023/11/17 11:21:15.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:15.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:16.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:16.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:17.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:17.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:18.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:18.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:19.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:19.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:20.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:20.066 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:21.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:21.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:22.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:22.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:23.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:23.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:24.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:24.066 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:25.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:25.066 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:26.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:26.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:26.646 +00:00] [INFO] [querycoordv2/services.go:144] ["show partitions request received"] [msgID=0] [collectionID=443795323898595897] [partitions="[443795323898596473,4437953238985
96476,443795323898596479]"]
[2023/11/17 11:21:27.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:27.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:28.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:28.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:29.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:29.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:30.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:30.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:31.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:31.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:32.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:32.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/17 11:21:33.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/17 11:21:33.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]

**Comment by yah01** [comment]
Hi @baosince, could you post your code so we can reproduce it?

Milvus doesn't go with strong consistency by default, you could set this while searching, or set it while creating collection.

So you can check the consistency level first

**Comment by baosince** [comment]
collection create param:
```
CreateCollectionParam createParam = CreateCollectionParam.newBuilder()
//                .withDatabaseName()
                .withCollectionName(collection)
                .withFieldTypes(fieldsSchema)
                .withShardsNum(2)
//                .withPartitionsNum(2)
                .withEnableDynamicField(true)
                .withDescription("知识库")
                .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
                .build();
```

delete param:
```
queryResultsR = milvusClient.query(QueryParam.newBuilder()
                    .withCollectionName(collection)
                    .withPartitionNames(partitionList)
                    .withExpr(expr)
                    .addOutField("id")
                    .withConsistencyLevel(ConsistencyLevelEnum.STRONG)
                    .build());
```

delete param:
```
deleteResponseR = milvusClient.delete(DeleteIdsParam.newBuilder()
                    .withCollectionName(collection)
                    .withPrimaryIds(Arrays.asList(StringUtils.listToStr("\"", ids).split(",")))
                    .build());
```
  
java sdk log:
```
###|||2023-11-18 13:07:37.331|||INFO|||4872a0cf2bac44569226e90dab2655d8.69.17002840571312947|||-|||http-nio-8080-exec-5|||-|||-|||AbstractMilvusGrpcClient--->DeleteIdsParam(collectionName=embedding015, primaryIds=["data-20231117191909xy", "data-2023111719190gih", "data-20231117191914dj", "data-2023111719192j92", "data-2023111719192o0t", "data-2023111719192tw9", "data-2023111719193bzg", "data-2023111719193s1z", "data-20231117191941id", "data-2023111719194kwc", "data-20231117191951yk", "data-2023111719196dw6", "data-20231117191976ve", "data-2023111719198r6r", "data-2023111719199xxd", "data-202311171919dha7", "data-202311171919eles", "data-202311171919f7jt", "data-202311171919gcls", "data-202311171919gdfw", "data-202311171919iirw", "data-202311171919jova", "data-202311171919kpyc", "data-202311171919kzl1", "data-202311171919lg62", "data-202311171919ltbk", "data-202311171919p0i6", "data-202311171919qh81", "data-202311171919ss32", "data-202311171919u67a", "data-202311171919uhz3", "data-202311171919ujg6", "data-202311171919usrn", "data-202311171919vqm5", "data-202311171919w08n", "data-202311171919w6ha", "data-202311171919x1um", "data-202311171919xiln", "data-202311171919xuxe"])
###|||2023-11-18 13:07:37.331|||INFO|||4872a0cf2bac44569226e90dab2655d8.69.17002840571312947|||-|||http-nio-8080-exec-5|||-|||-|||AbstractMilvusGrpcClient--->DescribeCollectionParam(databaseName=null, collectionName=embedding015)
###|||2023-11-18 13:07:37.343|||INFO|||4872a0cf2bac44569226e90dab2655d8.69.17002840571312947|||-|||http-nio-8080-exec-5|||-|||-|||AbstractMilvusGrpcClient--->DeleteParam{collectionName='embedding015', partitionName='', expr='id in ["data-20231117191909xy","data-2023111719190gih","data-20231117191914dj","data-2023111719192j92","data-2023111719192o0t","data-2023111719192tw9","data-2023111719193bzg","data-2023111719193s1z","data-20231117191941id","data-2023111719194kwc","data-20231117191951yk","data-2023111719196dw6","data-20231117191976ve","data-2023111719198r6r","data-2023111719199xxd","data-202311171919dha7","data-202311171919eles","data-202311171919f7jt","data-202311171919gcls","data-202311171919gdfw","data-202311171919iirw","data-202311171919jova","data-202311171919kpyc","data-202311171919kzl1","data-202311171919lg62","data-202311171919ltbk","data-202311171919p0i6","data-202311171919qh81","data-202311171919ss32","data-202311171919u67a","data-202311171919uhz3","data-202311171919ujg6","data-202311171919usrn","data-202311171919vqm5","data-202311171919w08n","data-202311171919w6ha","data-202311171919x1um","data-202311171919xiln","data-202311171919xuxe"]'}
```  

milvus-standalone pod log:
```
[2023/11/18 05:07:36.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/18 05:07:36.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/18 05:07:37.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/18 05:07:37.066 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/18 05:07:37.149 +00:00] [INFO] [querycoordv2/services.go:144] ["show partitions request received"] [msgID=0] [collectionID=443795323898595897] [partitions="[443795323898596473,443795323898596476,443795323898596479]"]
[2023/11/18 05:07:37.162 +00:00] [INFO] [proxy/meta_cache.go:751] ["no shard cache for collection, try to get shard leaders from QueryCoord"] [collectionName=embedding015]
[2023/11/18 05:07:37.162 +00:00] [INFO] [querycoordv2/services.go:871] ["get shard leaders request received"] [msgID=0] [collectionID=443795323898595897]
[2023/11/18 05:07:37.335 +00:00] [INFO] [querycoordv2/services.go:144] ["show partitions request received"] [msgID=0] [collectionID=443795323898595897] [partitions="[443795323898596473,443795323898596476,443795323898596479]"]
[2023/11/18 05:07:37.346 +00:00] [INFO] [proxy/impl.go:791] ["DescribeCollection received"] [traceID=3d3fd05a61fddec3] [role=proxy] [db=default] [collection=embedding015]
[2023/11/18 05:07:37.347 +00:00] [INFO] [proxy/impl.go:815] ["DescribeCollection enqueued"] [traceID=3d3fd05a61fddec3] [role=proxy] [MsgID=445719263918948354] [BeginTS=445719263918948354] [EndTS=445719263918948354] [db=default] [collection=embedding015]
[2023/11/18 05:07:37.347 +00:00] [INFO] [rootcoord/root_coord.go:1151] ["received request to describe collection"] [traceID=3d3fd05a61fddec3] ["collection name"=embedding015] [dbName=default] [id=0] [msgID=445719263918948354] [ts=18446744073709551615] [allowUnavailable=false]
[2023/11/18 05:07:37.347 +00:00] [INFO] [rootcoord/root_coord.go:1184] ["done to describe collection"] [traceID=3d3fd05a61fddec3] ["collection name"=embedding015] [dbName=default] [id=0] [msgID=445719263918948354] [ts=18446744073709551615] [allowUnavailable=false] [collection_id=443795323898595897]
[2023/11/18 05:07:37.347 +00:00] [INFO] [proxy/impl.go:846] ["DescribeCollection done"] [traceID=3d3fd05a61fddec3] [role=proxy] [MsgID=445719263918948354] [BeginTS=445719263918948354] [EndTS=445719263918948354] [db=default] [collection=embedding015]
[2023/11/18 05:07:38.066 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/18 05:07:38.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/18 05:07:39.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
[2023/11/18 05:07:39.067 +00:00] [INFO] [observers/collection_observer.go:156] ["observe partitions status"] [partitionNum=3]
[2023/11/18 05:07:40.067 +00:00] [INFO] [observers/collection_observer.go:119] ["observes partitions timeout"] [partitionNum=1]
```

**Comment by xiaofan-luan** [comment]
@baosince 
I think we've fixed couple of deleted related issues, like https://github.com/milvus-io/milvus/issues/24234
is there a way you can try 2.2.15 and see if this has already be fixed?
Otherwise we will try to reproduce this in house

**Comment by baosince** [comment]
have you released 2.2.15 at helm?

**Comment by yanliang567** [comment]
> have you released 2.2.15 at helm?

the default helm chart value points to v2.3.3, so you need to specify the image tag to v2.2.15 if you want to deploy v2.2.15 with helm

**Comment by baosince** [comment]
> @baosince I think we've fixed couple of deleted related issues, like #24234 is there a way you can try 2.2.15 and see if this has already be fixed? Otherwise we will try to reproduce this in house

This problem is still present in 2.2.15. 
helm install command:
`helm install milvus-standalone milvus/milvus -n milvus --set image.all.tag=v2.2.15 --set cluster.enabled=false --set standalone.persistence.persistentVolumeClaim.storageClass=nfs-client --set minio.persistence.storageClass=nfs-client --set etcd.persistence.storageClass=nfs-client --set etcd.replicaCount=1 --set minio.mode=standalone --set pulsar.enabled=false --set standalone.resources.limits.cpu=4 --set standalone.resources.limits.memory=8Gi --version=4.1.9 `

**Comment by yanliang567** [comment]
@baosince do you have duplicated PK entities in milvus?  please refer this [doc](https://github.com/milvus-io/milvus/tree/master/deployments/export-log) to export the whole Milvus logs for investigation

**Comment by baosince** [comment]
[milvus-log.zip](https://github.com/milvus-io/milvus/files/13408178/milvus-log.zip)

here are the logs.

The PK is generated based on the timestamp. In theory, no duplicated PK entities are created.

**Comment by yanliang567** [comment]
/assign @yah01 

@baosince one more question: how do you define that the deletion was not working? could you please share some code snippet?

**Comment by baosince** [comment]
> /assign @yah01
> 
> @baosince one more question: how do you define that the deletion was not working? could you please share some code snippet?

1.  a. After deleting data, the data can still be queried for many hours or more.
    b. Milvus didn't log any record about the deletion operation, such as `[proxy/impl.go:2892] ["Start processing delete request in Proxy"]`, `[proxy/task_delete.go:302] ["send delete request to virtual channels"]`

2. https://github.com/milvus-io/milvus/issues/28548#issuecomment-1817384349
this comment contains code snippet of CreateCollectionParam, QueryParam and DeleteIdsParam. Is this enough?

**Comment by baosince** [comment]
can u reproduce this

**Comment by yah01** [comment]
Some bug found and I'm working on this

**Comment by baosince** [comment]
> Some bug found and I'm working on this

I reproduce this in my new standalone environment, and find the Operation(internal/querynode/flow_graph_insert_node.go:86) method is not called.
