### ISSUE TITLE
[Bug]: Search failed a short time: unrecoverable error and node offline after removing pod-kill chaos on querynodes

### ISSUE THREAD

**Issue by ThreadDao** [milvus-io/milvus#30816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20240222-16b4c9a7
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy milvus with 3 queryNodes and 2 dataNodes
```
components:
        enableRollingUpdate: true
        imageUpdateMode: rollingUpgrade
```
```
chaos-delta-clu-insert-1-milvus-datanode-6b776bb79f-bntgc        Running     0            1m      10.104.5.158      4am-node12     
chaos-delta-clu-insert-1-milvus-datanode-6b776bb79f-th4vl        Running     0            1m      10.104.14.203     4am-node18     
chaos-delta-clu-insert-1-milvus-indexnode-7b47b86666-hbgc5       Running     0            1m      10.104.19.146     4am-node28     
chaos-delta-clu-insert-1-milvus-indexnode-7b47b86666-jfczw       Running     0            1m      10.104.6.99       4am-node13     
chaos-delta-clu-insert-1-milvus-mixcoord-69fb5f6f88-h8zkn        Running     0            1m      10.104.1.182      4am-node10     
chaos-delta-clu-insert-1-milvus-proxy-6fd8486888-rfmjq           Running     0            1m      10.104.13.211     4am-node16     
chaos-delta-clu-insert-1-milvus-querynode-0-5cf94558b9-btrvq     Running     0            1m      10.104.24.123     4am-node29     
chaos-delta-clu-insert-1-milvus-querynode-0-5cf94558b9-fhvsk     Running     0            1m      10.104.16.102     4am-node21     
chaos-delta-clu-insert-1-milvus-querynode-0-5cf94558b9-nl2lx     Running     0            1m      10.104.5.159      4am-node12  
```
2. start test at **2024-02-22 16:10**
create coll -> index -> load -> insert 3m-128d -> flush -> index again -> load again -> concurrent requests for 10hours: insert + delete + flush + search (from 2024-02-22 16:14 to 2024-02-23 02:14)
3.  chaos pod-kill all queryNodes and dataNodes **every two minutes** from 2024-02-22 18:10 to 2024-02-22 18:20. During chaos, all search/query requests succ.
4. search/query failed after remove chaos at around `2024-02-22 18:20`
```
[2024-02-22 18:40:05,664 - ERROR - fouram]: RPC error: [search], <MilvusException: (code=65535, message=unrecoverable error)>, <Time:{'RPC start': '2024-02-22 18:40:05.054253', 'RPC error': '2024-02-22 18:40:05.664809'}> (decorators.py:134)

[2024-02-22 18:41:33,748 - ERROR - fouram]: (api_response) : [Collection.search] <MilvusException: (code=503, message=failed to search: segment lacks[segment=447903965656824986]: channel not available[channel=chaos-delta-clu-insert-1-rootcoord-dml_0_447903965656384378v0])>, [requestId: 00705bf6-d1b2-11ee-802d-1ea479a7acc9] (api_request.py:57)

```

### Milvus Log

Loki:  [some logs](https://grafana-4am.zilliz.cc/explore?panes=%7B%22Qa9%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa-milvus%5C%22,%20pod%3D~%5C%22chaos-delta-clu-insert-1-milvus-querynode-.%2A%5C%22%7D%20%7C%3D%20%5C%22GitCommit%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa-milvus%5C%22,%20pod%3D~%5C%22chaos-delta-clu-insert-1-milvus-proxy-6fd8486888-rfmjq%5C%22%7D%20%7C%3D%20%5C%22search%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D,%7B%22refId%22:%22D%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa-milvus%5C%22,%20pod%3D~%5C%22chaos-delta-clu-insert-1-milvus-querynode-.%2A%5C%22%7D%20%7C%3D%20%5C%22e8226f465a4c4012d8316b85909bb4c9%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221708625400000%22,%22to%22:%221708626000000%22%7D%7D,%22Mys%22:%7B%22datasource%22:%22Nlp-rIJ4k%22,%22queries%22:%5B%7B%22queryType%22:%22traceql%22,%22refId%22:%22A%22,%22limit%22:20,%22tableType%22:%22traces%22,%22query%22:%22e8226f465a4c4012d8316b85909bb4c9%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22Nlp-rIJ4k%22%7D%7D%5D,%22range%22:%7B%22from%22:%221708625400000%22,%22to%22:%221708626000000%22%7D%7D%7D&schemaVersion=1&orgId=1)
grafana: [metric](https://grafana-4am.zilliz.cc/d/uLf5cJ3Ga/milvus2-0?orgId=1&from=1708617307022&to=1708669331413&var-datasource=P1809F7CD0C75ACF3&var-cluster=&var-namespace=qa-milvus&var-instance=chaos-delta-clu-insert-1&var-collection=All&var-app_name=milvus)
argo: https://argo-workflows.zilliz.cc/archived-workflows/qa/c058564e-e919-43fb-b8ce-70a532d24443?nodeId=fouramf-chaos-delta-cluster-insert-2a
client debug log path: /test/fouram/log/2024_02_22/fouramf-chaos-delta-cluster-insert-2a-fouramf-client_72549/test_concurrent_locust_custom_parameters/fouram_log.debug

**Comment by weiliu1031** [comment]
![image](https://github.com/milvus-io/milvus/assets/108661493/d7c98684-1cf4-4a8a-bf1b-a30246c6d91c)
known issue, should be fixed by #30258

**Comment by weiliu1031** [comment]
please verify this with latest image

**Comment by ThreadDao** [comment]
fixed image: `master-20240304-52540fec-amd64`

**Comment by ThreadDao** [comment]
/unassign
/assign @weiliu1031 
not fixed yet
- image: master-20240311-a99143dd
- argo workflow: https://argo-workflows.zilliz.cc/workflows/qa/fouramf-chaos-level-kill-insert-wr4?tab=workflow&nodeId=fouramf-chaos-level-kill-insert-wr4&nodePanelView=containers
- release name: kill-level-clu-insert-wr4
- recover chaos  at 2024-03-11 12:06, but client logs shows that search failed during 12:26 ~ 12:36
[client search error logs](https://grafana-4am.zilliz.cc/explore?panes=%7B%22Qa9%22:%7B%22datasource%22:%22vhI6Vw67k%22,%22queries%22:%5B%7B%22refId%22:%22C%22,%22expr%22:%22%7Bcluster%3D%5C%224am%5C%22,%20namespace%3D%5C%22qa%5C%22,%20pod%3D%5C%22fouramf-chaos-level-kill-insert-wr4-557092692%5C%22%7D%20%7C%3D%20%5C%22ERROR%5C%22%20%7C%3D%20%5C%22Collection.search%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22vhI6Vw67k%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221710158403204%22,%22to%22:%221710161154362%22%7D%7D%7D&schemaVersion=1&orgId=1)

**Comment by ThreadDao** [comment]
@weiliu1031 not fixed yet
- image: master-20240326-248c923e-amd64
chaos: 12:59:48 - 13:11:00
search failed period: 13:00:08 - 14:00:00
- argo:  https://argo-workflows.zilliz.cc/archived-workflows/qa/af7eba3e-f032-4f63-a611-6e1b46250189?nodeId=fouramf-chaos-level-kill-insert-vv
- pods:
```
kill-level-clu-insert-vv-etcd-0                                   1/1     Running                           0               4h57m   10.104.30.230   4am-node38   <none>           <none>
kill-level-clu-insert-vv-etcd-1                                   1/1     Running                           0               4h57m   10.104.16.31    4am-node21   <none>           <none>
kill-level-clu-insert-vv-etcd-2                                   1/1     Running                           0               4h57m   10.104.21.177   4am-node24   <none>           <none>
kill-level-clu-insert-vv-milvus-datanode-55d54d6f57-d848q         1/1     Running                           0               3h40m   10.104.1.32     4am-node10   <none>           <none>
kill-level-clu-insert-vv-milvus-datanode-55d54d6f57-fmqtj         1/1     Running                           0               3h40m   10.104.14.13    4am-node18   <none>           <none>
kill-level-clu-insert-vv-milvus-indexnode-844cdf8cb6-jkk6r        1/1     Running                           0               4h53m   10.104.4.213    4am-node11   <none>           <none>
kill-level-clu-insert-vv-milvus-indexnode-844cdf8cb6-n76kq        1/1     Running                           0               4h53m   10.104.5.215    4am-node12   <none>           <none>
kill-level-clu-insert-vv-milvus-mixcoord-68c9f9f586-mm2kv         1/1     Running                           0               4h53m   10.104.13.146   4am-node16   <none>           <none>
kill-level-clu-insert-vv-milvus-proxy-686f597f7d-6z2xd            1/1     Running                           0               4h53m   10.104.13.145   4am-node16   <none>           <none>
kill-level-clu-insert-vv-milvus-querynode-0-54cc564df9-h2g8h      1/1     Running                           0               3h40m   10.104.13.174   4am-node16   <none>           <none>
kill-level-clu-insert-vv-milvus-querynode-0-54cc564df9-k82r8      1/1     Running                           0               3h40m   10.104.29.27    4am-node35   <none>           <none>
kill-level-clu-insert-vv-milvus-querynode-0-54cc564df9-zn5q4      1/1     Running                           0               3h40m   10.104.1.31     4am-node10   <none>           <none>
kill-level-clu-insert-vv-minio-0                                  1/1     Running                           0               4h57m   10.104.30.231   4am-node38   <none>           <none>
kill-level-clu-insert-vv-minio-1                                  1/1     Running                           0               4h57m   10.104.20.5     4am-node22   <none>           <none>
kill-level-clu-insert-vv-minio-2                                  1/1     Running                           0               4h57m   10.104.29.242   4am-node35   <none>           <none>
kill-level-clu-insert-vv-minio-3                                  1/1     Running                           0               4h57m   10.104.21.178   4am-node24   <none>           <none>
kill-level-clu-insert-vv-pulsar-bookie-0                          1/1     Running                           0               4h57m   10.104.30.232   4am-node38   <none>           <none>
kill-level-clu-insert-vv-pulsar-bookie-1                          1/1     Running                           0               4h57m   10.104.29.244   4am-node35   <none>           <none>
kill-level-clu-insert-vv-pulsar-bookie-2                          1/1     Running                           0               4h57m   10.104.20.9     4am-node22   <none>           <none>
kill-level-clu-insert-vv-pulsar-bookie-init-hg7gp                 0/1     Completed                         0               4h57m   10.104.14.242   4am-node18   <none>           <none>
kill-level-clu-insert-vv-pulsar-broker-0                          1/1     Running                           0               4h57m   10.104.14.243   4am-node18   <none>           <none>
kill-level-clu-insert-vv-pulsar-proxy-0                           1/1     Running                           0               4h57m   10.104.4.212    4am-node11   <none>           <none>
kill-level-clu-insert-vv-pulsar-pulsar-init-dk25w                 0/1     Completed                         0               4h57m   10.104.4.208    4am-node11   <none>           <none>
kill-level-clu-insert-vv-pulsar-recovery-0                        1/1     Running                           0               4h57m   10.104.4.211    4am-node11   <none>           <none>
kill-level-clu-insert-vv-pulsar-zookeeper-0                       1/1     Running                           0               4h57m   10.104.30.233   4am-node38   <none>           <none>
kill-level-clu-insert-vv-pulsar-zookeeper-1                       1/1     Running                           0               4h56m   10.104.21.184   4am-node24   <none>           <none>
kill-level-clu-insert-vv-pulsar-zookeeper-2                       1/1     Running                           0               4h56m   10.104.25.46    4am-node30   <none>           <none>
```

**Comment by weiliu1031** [comment]
> kill-level-clu-insert-vv-milvus

should be fixed by #31540, please verify it with latest image

**Comment by ThreadDao** [comment]
fixed `Image: 2.4-20240327-d37e1fdd-amd64`
[fouramf-chaos-level-kill-insert-vv2](https://argo-workflows.zilliz.cc/archived-workflows/qa/ddbf32a9-a732-442f-8c35-72c7a19354e6?nodeId=fouramf-chaos-level-kill-insert-vv2)

Search failed period: 03:28:16 - 04:06:29
The out-of-service time after the chaos is removed is 30 minutes

**Comment by weiliu1031** [comment]
please verify this with latest image

**Comment by ThreadDao** [comment]
@weiliu1031 
fixed image: 2.4-20240409-f0b41535-amd64
- chaos period: 05:02:00 - 05:12:05
- search failed period: 05:04:13 - 05:08:53
- argo workflow: https://argo-workflows.zilliz.cc/archived-workflows/qa/86731285-2ed9-4f1b-82b3-c6339b4f2caf?nodeId=zong-chaos-cluster-jbjk
![image](https://github.com/milvus-io/milvus/assets/27288593/051ff2fa-a6f9-4f24-9ac8-e74af45ba82c)
