### ISSUE TITLE
[Bug]: After transferring replicas to new query nodes, the segments still remain on the old query nodes.

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#32862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240507-53874ce2-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
                                                                                   Resource Group Info                                                                                    
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                     ┃ Capacity ┃ Available Node ┃ Loaded Replica           ┃ Outgoing Node ┃ Incoming Node ┃ Request ┃ Limit ┃ Nodes                                              ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ __default_resource_group │ 1000000  │ 3              │ {'Checker__CP8UzgWo': 1} │ {}            │ {}            │ 0       │ 10    │ rg-test-234937-milvus-querynode-0-855647b8bd-lc2mn │
│                          │          │                │                          │               │               │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2 │
│                          │          │                │                          │               │               │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-ljcg9 │
│ rg_85hmeHMP              │ 2        │ 2              │ {}                       │ {}            │ {}            │ 2       │ 2     │ rg-test-234937-milvus-querynode-0-855647b8bd-98w54 │
│                          │          │                │                          │               │               │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-972bw │
└──────────────────────────┴──────────┴────────────────┴──────────────────────────┴───────────────┴───────────────┴─────────┴───────┴────────────────────────────────────────────────────┘
                                                     Checker__CP8UzgWo Segment Distribution Info                                                      
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Segment ID         ┃ Collection ID      ┃ Partition ID       ┃ Num Rows ┃ State ┃ Node ID ┃ Node Name                                              ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 449618054847598736 │ 449618054847398552 │ 449618054847398553 │ 627      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598735 │ 449618054847398552 │ 449618054847398553 │ 608      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598732 │ 449618054847398552 │ 449618054847398553 │ 606      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598733 │ 449618054847398552 │ 449618054847398553 │ 562      │ 3     │ [9]     │ ['rg-test-234937-milvus-querynode-0-855647b8bd-ljcg9'] │
│ 449618054847598734 │ 449618054847398552 │ 449618054847398553 │ 597      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
└────────────────────┴────────────────────┴────────────────────┴──────────┴───────┴─────────┴────────────────────────────────────────────────────────┘
                                                                                              Resource Group Info                                                                                               
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                     ┃ Capacity ┃ Available Node ┃ Loaded Replica           ┃ Outgoing Node            ┃ Incoming Node            ┃ Request ┃ Limit ┃ Nodes                                              ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ __default_resource_group │ 1000000  │ 3              │ {}                       │ {}                       │ {'Checker__CP8UzgWo': 3} │ 0       │ 10    │ rg-test-234937-milvus-querynode-0-855647b8bd-lc2mn │
│                          │          │                │                          │                          │                          │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2 │
│                          │          │                │                          │                          │                          │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-ljcg9 │
│ rg_85hmeHMP              │ 2        │ 2              │ {'Checker__CP8UzgWo': 1} │ {'Checker__CP8UzgWo': 3} │ {}                       │ 2       │ 2     │ rg-test-234937-milvus-querynode-0-855647b8bd-98w54 │
│                          │          │                │                          │                          │                          │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-972bw │
└──────────────────────────┴──────────┴────────────────┴──────────────────────────┴──────────────────────────┴──────────────────────────┴─────────┴───────┴────────────────────────────────────────────────────┘
                                                     Checker__CP8UzgWo Segment Distribution Info                                                      
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Segment ID         ┃ Collection ID      ┃ Partition ID       ┃ Num Rows ┃ State ┃ Node ID ┃ Node Name                                              ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 449618054847598736 │ 449618054847398552 │ 449618054847398553 │ 627      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598733 │ 449618054847398552 │ 449618054847398553 │ 562      │ 3     │ [9]     │ ['rg-test-234937-milvus-querynode-0-855647b8bd-ljcg9'] │
│ 449618054847598735 │ 449618054847398552 │ 449618054847398553 │ 608      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598732 │ 449618054847398552 │ 449618054847398553 │ 606      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598734 │ 449618054847398552 │ 449618054847398553 │ 597      │ 3     │ [11]    │ ['rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
└────────────────────┴────────────────────┴────────────────────┴──────────┴───────┴─────────┴────────────────────────────────────────────────────────┘
[2024-05-08 16:31:58 - INFO - ci_test]: SearchChecker, succ_rate: 1.00, total: 120, average_time: 0.5254, max_time: 0.8168, min_time: 0.2775 (checker.py:439)
                                                                                   Resource Group Info                                                                                    
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Name                     ┃ Capacity ┃ Available Node ┃ Loaded Replica           ┃ Outgoing Node ┃ Incoming Node ┃ Request ┃ Limit ┃ Nodes                                              ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ __default_resource_group │ 1000000  │ 3              │ {}                       │ {}            │ {}            │ 0       │ 10    │ rg-test-234937-milvus-querynode-0-855647b8bd-lc2mn │
│                          │          │                │                          │               │               │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2 │
│                          │          │                │                          │               │               │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-ljcg9 │
│ rg_85hmeHMP              │ 2        │ 2              │ {'Checker__CP8UzgWo': 1} │ {}            │ {}            │ 2       │ 2     │ rg-test-234937-milvus-querynode-0-855647b8bd-972bw │
│                          │          │                │                          │               │               │         │       │ rg-test-234937-milvus-querynode-0-855647b8bd-98w54 │
└──────────────────────────┴──────────┴────────────────┴──────────────────────────┴───────────────┴───────────────┴─────────┴───────┴────────────────────────────────────────────────────┘
                                                                                Checker__CP8UzgWo Segment Distribution Info                                                                                 
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Segment ID         ┃ Collection ID      ┃ Partition ID       ┃ Num Rows ┃ State ┃ Node ID ┃ Node Name                                                                                                    ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 449618054847598733 │ 449618054847398552 │ 449618054847398553 │ 562      │ 3     │ [2, 9]  │ ['rg-test-234937-milvus-querynode-0-855647b8bd-98w54', 'rg-test-234937-milvus-querynode-0-855647b8bd-ljcg9'] │
│ 449618054847598735 │ 449618054847398552 │ 449618054847398553 │ 608      │ 3     │ [2, 11] │ ['rg-test-234937-milvus-querynode-0-855647b8bd-98w54', 'rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598736 │ 449618054847398552 │ 449618054847398553 │ 627      │ 3     │ [2, 11] │ ['rg-test-234937-milvus-querynode-0-855647b8bd-98w54', 'rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598734 │ 449618054847398552 │ 449618054847398553 │ 597      │ 3     │ [2, 11] │ ['rg-test-234937-milvus-querynode-0-855647b8bd-98w54', 'rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
│ 449618054847598732 │ 449618054847398552 │ 449618054847398553 │ 606      │ 3     │ [2, 11] │ ['rg-test-234937-milvus-querynode-0-855647b8bd-98w54', 'rg-test-234937-milvus-querynode-0-855647b8bd-hb9v2'] │
└────────────────────┴────────────────────┴────────────────────┴──────────┴───────┴─────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

### Expected Behavior

segments on the old resource group were offloaded

### Anything else?

transfer replicas happened in 08:31
querynode memory usage in source rg
![image](https://github.com/milvus-io/milvus/assets/12268675/7379dfbf-a013-4953-95e3-2135afd366ef)

querynode memory usage in target rg
![image](https://github.com/milvus-io/milvus/assets/12268675/8cb9acfa-8e12-4a0d-940a-2fd5ea05ec96)

After the transfer replicase occurred, the memory of the target RG's query node increased, but the source RG's query node did not decrease.

**Comment by xiaofan-luan** [comment]
I think this is async transfer.
you may need a while to finish the balance

**Comment by zhuwenxing** [comment]
![image](https://github.com/milvus-io/milvus/assets/12268675/4196eaa6-5b2a-4011-9ee5-110f2e47bae6)

In another test, the memory of the source RG experienced some decline, but according to the segment distribution obtained through the interface utility.get_query_segment_info(collection_name), it was found that the segments still existed on the query node of the source RG.

![image](https://github.com/milvus-io/milvus/assets/12268675/a46f4fed-03ce-4971-a50b-25a169073796)

**Comment by weiliu1031** [comment]
same problems with #32901, should be fixed by #32929

**Comment by weiliu1031** [comment]
please verify this with latest image

**Comment by zhuwenxing** [comment]
test job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/resource_group_test/detail/resource_group_test/8/pipeline

During this test, the information obtained through the get query segment info interface indicates that after the transfer, the segment is only present in the target's rg. However, in the Grafana monitoring, it shows that the segment still exists in the source rg.
![image](https://github.com/milvus-io/milvus/assets/12268675/31f8594f-acce-4203-bda7-87b6d3a00ade)


After the transfer occurred, although the number of loaded segments experienced a decrease, it did not fully drop to zero; instead, some segments remained and did not decrease any further.
![image](https://github.com/milvus-io/milvus/assets/12268675/60278ec4-ca50-4d33-a583-584cad37c2dd)

**Comment by zhuwenxing** [comment]
> test job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/resource_group_test/detail/resource_group_test/8/pipeline
> 
> During this test, the information obtained through the get query segment info interface indicates that after the transfer, the segment is only present in the target's rg. However, in the Grafana monitoring, it shows that the segment still exists in the source rg. ![image](https://private-user-images.githubusercontent.com/12268675/329748648-31f8594f-acce-4203-bda7-87b6d3a00ade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTY3MDAsIm5iZiI6MTcxNTg1NjQwMCwicGF0aCI6Ii8xMjI2ODY3NS8zMjk3NDg2NDgtMzFmODU5NGYtYWNjZS00MjAzLWJkYTctODdiNmQzYTAwYWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwNDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZTA4MzBiZTVlMzdkOTdjZGVlNmJhYmQxOTUzMzg5NWM2Nzk0ZmVmZDc2YzUxOTJkNmI5NTIwNzM3NTZlNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jZvlHDzmNVIjt2CF0ISEbMl34YPUki8QT2mF7n-ejew)
> 
> After the transfer occurred, although the number of loaded segments experienced a decrease, it did not fully drop to zero; instead, some segments remained and did not decrease any further. ![image](https://private-user-images.githubusercontent.com/12268675/329748827-60278ec4-ca50-4d33-a583-584cad37c2dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NTY3MDAsIm5iZiI6MTcxNTg1NjQwMCwicGF0aCI6Ii8xMjI2ODY3NS8zMjk3NDg4MjctNjAyNzhlYzQtY2E1MC00ZDMzLWE1ODMtNTg0Y2FkMzdjMmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDEwNDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwM2VjNzUzOTM3MzIzNDZkYThlYjgxZmU1NjkxZmNkOWI5ZmJkNTczYzI5YTg0MjY3ZWI5NjgwOWViNTg3NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DOreRZJk58i2lK4Ff9NIDubpTtK7knvMvHbW979vFes)



@weiliu1031 
please take a look
