### ISSUE TITLE
[Feature]: Ask for Bfloat16 data type insert.

### ISSUE THREAD

**Issue by mellonyou** [milvus-io/milvus#36468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Have added bfloat16 support in knowhere, and query performance have a significate improve. But, directly writing bf16 data type, which need to be converted to bytes, it will results in poor performance.

### Describe the solution you'd like.

Can write bfloat16 data type directly without type convert.

**Comment by xiaofan-luan** [comment]
which SDk are u using?
Many of the language don't have Bf16 as datatype, that's why we convert it to binary

**Comment by mellonyou** [comment]
I test it with python script, and I want to use milvus to receive bf16 data from langchain.

**Comment by xiaofan-luan** [comment]
> I test it with python script, and I want to use milvus to receive bf16 data from langchain.

Did langchain support BF16 embedding already?

**Comment by zc277584121** [comment]
As far as I know, langchain itself does not involve data type processing, but generally some deep learning frameworks such as tf, pytorch can generate bf16. @mellonyou  Can you  please explain your scenario in detail? Are you trying to use langchain_milvus to do this?

**Comment by congqixia** [comment]
Maybe the need is to integrate langchain output direct into milvus collection with BFloat16 field, which means the input vector is float32 and let Milvus server do the data type conversion internally

**Comment by zc277584121** [comment]
@mellonyou Thank you for your feedback. We will verify the feasibility and try to add some features to meet this requirement in later versions of langchain_milvus.

**Comment by zc277584121** [comment]
@mellonyou We have released a new version of langchain_milvus==0.1.6, which supports customized vector field schema. You can upgrade your package and try this feature.  Here is an example: https://github.com/langchain-ai/langchain-milvus/blob/54c8167cea9e2bc73a467566b5fbc3da2d44f7cf/libs/milvus/tests/integration_tests/vectorstores/test_milvus.py#L416

**Comment by xtangxtang** [comment]
> @mellonyou We have released a new version of langchain_milvus==0.1.6, which supports customized vector field schema. You can upgrade your package and try this feature. Here is an example: https://github.com/langchain-ai/langchain-milvus/blob/54c8167cea9e2bc73a467566b5fbc3da2d44f7cf/libs/milvus/tests/integration_tests/vectorstores/test_milvus.py#L416

@zc277584121 does this means Milvus from main branch can support bf16?

**Comment by zc277584121** [comment]
@xtangxtang Yes, milvus can support bf16 already, here is the examples
https://milvus.io/docs/release_notes.md#Float16-and-BFloat--Vector-DataType

**Comment by xtangxtang** [comment]
> @xtangxtang Yes, milvus can support bf16 already, here is the examples https://milvus.io/docs/release_notes.md#Float16-and-BFloat--Vector-DataType

@zc277584121 Thanks

**Comment by Tensionteng** [comment]
I still don't know how to insert a bfloat16（PyTorch） vector to milvus. The link you offer does not offer a clear example. Can you offer another link with more details?

**Comment by xiaofan-luan** [comment]
> I still don't know how to insert a bfloat16（PyTorch） vector to milvus. The link you offer does not offer a clear example. Can you offer another link with more details?

you could use this function to convert into milvus bf16

 bf16_vector = tf.cast(raw_vector, dtype=tf.bfloat16).numpy()

or    

 bf16_vector = float_vector.to(torch.bfloat16).numpy()

**Comment by Tensionteng** [comment]
> > I still don't know how to insert a bfloat16（PyTorch） vector to milvus. The link you offer does not offer a clear example. Can you offer another link with more details?
> 
> you could use this function to convert into milvus bf16
> 
> bf16_vector = tf.cast(raw_vector, dtype=tf.bfloat16).numpy()
> 
> or
> 
> bf16_vector = float_vector.to(torch.bfloat16).numpy()

Thanks a lot, but actually I have seen the [example](https://github.com/milvus-io/milvus-lite/blob/main/examples/bfloat16_example.py) in this repo, I am looking for a pure pytorch (both tf and paddle can do) method to solve this issue, but I can't find.
