### ISSUE TITLE
[Bug]: datanode panic during test after querynode pod failure chaos test

### ISSUE THREAD

**Issue by zhuwenxing** [milvus-io/milvus#43073]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20250701-c381bf3e-amd64
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
[2025/07/02 03:35:45.112 +00:00] [DEBUG] [datanode/index_services.go:477] ["query stats job result success"] [traceID=4851f83af7fd59719bb2e4951b40cf09] [clusterID=by-dev] [taskIDs="[459125153185249027]"] [results="[{\"taskID\":459125153185249027,\"state\":2,\"collectionID\":459125153147332841,\"partitionID\":459125153147332842,\"segmentID\":459125153185249026,\"channel\":\"by-dev-rootcoord-dml_5_459125153147332841v0\",\"insert_logs\":[{\"fieldID\":113,\"binlogs\":[{\"entries_num\":2262,\"timestamp_to\":459126032102850569,\"log_size\":1158656,\"logID\":459125153187651938,\"memory_size\":1158656}]},{\"binlogs\":[{\"entries_num\":2262,\"timestamp_to\":459126032102850569,\"log_size\":7286590,\"logID\":459125153187651934,\"memory_size\":7286590}]},{\"fieldID\":110,\"binlogs\":[{\"entries_num\":2262,\"timestamp_to\":459126032102850569,\"log_size\":1158656,\"logID\":459125153187651935,\"memory_size\":1158656}]},{\"fieldID\":111,\"binlogs\":[{\"entries_num\":2262,\"timestamp_to\":459126032102850569,\"log_size\":290048,\"logID\":459125153187651936,\"memory_size\":290048}]},{\"fieldID\":112,\"binlogs\":[{\"entries_num\":2262,\"timestamp_to\":459126032102850569,\"log_size\":404300,\"logID\":459125153187651937,\"memory_size\":404300}]}],\"stats_logs\":[{\"fieldID\":100,\"binlogs\":[{\"entries_num\":2262,\"log_size\":9230,\"logID\":459125153187651939,\"memory_size\":9230}]}],\"num_rows\":2262,\"bm25_logs\":[{\"fieldID\":112,\"binlogs\":[{\"entries_num\":2262,\"log_size\":15500,\"logID\":459125153187651940,\"memory_size\":15500}]}]}]"]
[2025/07/02 03:35:45.114 +00:00] [INFO] [datanode/services.go:823] ["DropTask received"] [traceID=e2d2e307180712ab04232a8336646057] [properties="{\"cluster_id\":\"by-dev\",\"task_id\":\"459125153186575830\",\"task_type\":\"Index\"}"]
[2025/07/02 03:35:45.114 +00:00] [INFO] [datanode/index_services.go:541] ["DataNode receive DropJobs request"] [traceID=e2d2e307180712ab04232a8336646057] [clusterID=by-dev] [taskIDs="[459125153186575830]"] [jobType=JobTypeIndexJob]
[2025/07/02 03:35:45.114 +00:00] [INFO] [index/task_manager.go:173] ["delete task infos"] [traceID=e2d2e307180712ab04232a8336646057] [cluster_id=by-dev] [build_id=459125153186575830]
[2025/07/02 03:35:45.114 +00:00] [INFO] [datanode/index_services.go:555] ["drop index build jobs success"] [traceID=e2d2e307180712ab04232a8336646057] [clusterID=by-dev] [taskIDs="[459125153186575830]"] [jobType=JobTypeIndexJob]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3fd2425]

goroutine 3822 gp=0xc000ed1500 m=30 mp=0xc002581808 [running]:
panic({0x5a05f00?, 0x90d72b0?})
	/usr/local/go/src/runtime/panic.go:811 +0x168 fp=0xc001c75018 sp=0xc001c74f68 pc=0x1f6a828
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.deferwrap1()
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.28.0/trace/span.go:398 +0x25 fp=0xc001c75038 sp=0xc001c75018 pc=0x2a269a5
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc002b3eb60, {0x0, 0x0, 0xc000ed1500?})
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.28.0/trace/span.go:436 +0xa59 fp=0xc001c75318 sp=0xc001c75038 pc=0x2a26919
github.com/milvus-io/milvus/internal/datanode/index.(*statsTask).Execute.deferwrap1()
	/workspace/source/internal/datanode/index/task_stats.go:298 +0x2c fp=0xc001c75348 sp=0xc001c75318 pc=0x48cf88c
panic({0x5a05f00?, 0x90d72b0?})
	/usr/local/go/src/runtime/panic.go:792 +0x132 fp=0xc001c753f8 sp=0xc001c75348 pc=0x1f6a7f2
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:262
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:925 +0x359 fp=0xc001c75458 sp=0xc001c753f8 pc=0x1f6dad9
github.com/milvus-io/milvus/internal/storage.(*packedRecordWriter).Close(...)
	/workspace/source/internal/storage/serde_events_v2.go:203
github.com/milvus-io/milvus/internal/storage.(*PackedBinlogRecordWriter).Close(0xc001d473b0)
	/workspace/source/internal/storage/serde_events_v2.go:383 +0x45 fp=0xc001c75470 sp=0xc001c75458 pc=0x3fd2425
github.com/milvus-io/milvus/internal/datanode/index.(*statsTask).sort(0xc000b72480, {0x691ff28, 0xc002736ea0})
	/workspace/source/internal/datanode/index/task_stats.go:253 +0x1578 fp=0xc001c75c10 sp=0xc001c75470 pc=0x48cda58
github.com/milvus-io/milvus/internal/datanode/index.(*statsTask).Execute(0xc000b72480, {0x691ff60, 0xc002c32230})
	/workspace/source/internal/datanode/index/task_stats.go:303 +0x1fa fp=0xc001c75db8 sp=0xc001c75c10 pc=0x48cf1da
github.com/milvus-io/milvus/internal/datanode/index.Task.Execute-fm({0x691ff60?, 0xc002c32230?})
	<autogenerated>:1 +0x38 fp=0xc001c75de0 sp=0xc001c75db8 pc=0x48d9af8
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).processTask.func1(...)
	/workspace/source/internal/datanode/index/scheduler.go:236
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).processTask(0xc002192940, {0x694d7a8, 0xc000b72480}, {0xc002c04500?, 0xc000ecb1d0?})
	/workspace/source/internal/datanode/index/scheduler.go:249 +0x350 fp=0xc001c75f88 sp=0xc001c75de0 pc=0x48c1fb0
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).indexBuildLoop.func1({0x694d7a8?, 0xc000b72480?})
	/workspace/source/internal/datanode/index/scheduler.go:272 +0x31 fp=0xc001c75fc0 sp=0xc001c75f88 pc=0x48c25f1
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).indexBuildLoop.gowrap2()
	/workspace/source/internal/datanode/index/scheduler.go:273 +0x28 fp=0xc001c75fe0 sp=0xc001c75fc0 pc=0x48c2588
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc001c75fe8 sp=0xc001c75fe0 pc=0x1f74261
created by github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).indexBuildLoop in goroutine 348
	/workspace/source/internal/datanode/index/scheduler.go:271 +0xb5
```

```
 querynode-pod-failure-21648-etcd-0                                1/1     Running             0               67m     10.104.15.19    4am-node20   <none>           <none>
 querynode-pod-failure-21648-etcd-1                                1/1     Running             0               67m     10.104.17.40    4am-node23   <none>           <none>
 querynode-pod-failure-21648-etcd-2                                1/1     Running             0               67m     10.104.21.69    4am-node24   <none>           <none>
 querynode-pod-failure-21648-milvus-datanode-6cb8cd5dcd-pjzxm      0/1     CrashLoopBackOff    8 (82s ago)     67m     10.104.19.31    4am-node28   <none>           <none>
 querynode-pod-failure-21648-milvus-datanode-6cb8cd5dcd-sfj5c      0/1     CrashLoopBackOff    8 (25s ago)     67m     10.104.16.187   4am-node21   <none>           <none>
 querynode-pod-failure-21648-milvus-mixcoord-559d964df5-mlc92      0/1     Running             4 (3s ago)      67m     10.104.32.252   4am-node39   <none>           <none>
 querynode-pod-failure-21648-milvus-proxy-547f9bc98f-n9x8m         1/1     Running             3 (66m ago)     67m     10.104.32.251   4am-node39   <none>           <none>
 querynode-pod-failure-21648-milvus-querynode-76479d66b9-t8xcc     1/1     Running             6 (42m ago)     67m     10.104.23.193   4am-node27   <none>           <none>
 querynode-pod-failure-21648-milvus-querynode-76479d66b9-tr9tf     1/1     Running             6 (42m ago)     67m     10.104.6.52     4am-node13   <none>           <none>
 querynode-pod-failure-21648-milvus-querynode-76479d66b9-xx9lc     1/1     Running             6 (42m ago)     67m     10.104.25.183   4am-node30   <none>           <none>
 querynode-pod-failure-21648-milvus-streamingnode-c676864cdrmjlk   0/1     Error               6 (5m25s ago)   67m     10.104.22.99    4am-node26   <none>           <none>
 querynode-pod-failure-21648-milvus-streamingnode-c676864cdxd54z   0/1     Error               6 (5m14s ago)   67m     10.104.9.58     4am-node14   <none>           <none>
 querynode-pod-failure-21648-minio-0                               1/1     Running             0               67m     10.104.15.20    4am-node20   <none>           <none>
 querynode-pod-failure-21648-minio-1                               1/1     Running             0               67m     10.104.21.72    4am-node24   <none>           <none>
 querynode-pod-failure-21648-minio-2                               1/1     Running             0               67m     10.104.30.47    4am-node38   <none>           <none>
 querynode-pod-failure-21648-minio-3                               1/1     Running             0               67m     10.104.17.53    4am-node23   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-0                     1/1     Running             0               67m     10.104.21.67    4am-node24   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-1                     1/1     Running             0               67m     10.104.17.42    4am-node23   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-2                     1/1     Running             0               67m     10.104.30.46    4am-node38   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-init-fvbtb            0/1     Completed           0               67m     10.104.13.20    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-broker-0                     1/1     Running             0               67m     10.104.13.22    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-broker-1                     1/1     Running             0               67m     10.104.14.129   4am-node18   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-proxy-0                      1/1     Running             0               67m     10.104.13.19    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-proxy-1                      1/1     Running             0               67m     10.104.14.128   4am-node18   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-pulsar-init-hvnxm            0/1     Completed           0               67m     10.104.13.18    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-recovery-0                   1/1     Running             0               67m     10.104.13.15    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-zookeeper-0                  1/1     Running             0               67m     10.104.15.17    4am-node20   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-zookeeper-1                  1/1     Running             0               67m     10.104.21.68    4am-node24   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-zookeeper-2                  1/1     Running             0               67m     10.104.17.43    4am-node23   <none>           <none>
```

### Steps To Reproduce

```markdown

```

### Milvus Log

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21648/pipeline
log: 

[artifacts-querynode-pod-failure-21648-server-logs.tar.gz](https://github.com/user-attachments/files/21012862/artifacts-querynode-pod-failure-21648-server-logs.tar.gz)

cluster: 4am
ns: chaos-testing
pods
```
 + + kubectl get pods -ogrep wide querynode-pod-failure-21648
 
 querynode-pod-failure-21648-etcd-0                                1/1     Running             0               67m     10.104.15.19    4am-node20   <none>           <none>
 querynode-pod-failure-21648-etcd-1                                1/1     Running             0               67m     10.104.17.40    4am-node23   <none>           <none>
 querynode-pod-failure-21648-etcd-2                                1/1     Running             0               67m     10.104.21.69    4am-node24   <none>           <none>
 querynode-pod-failure-21648-milvus-datanode-6cb8cd5dcd-pjzxm      0/1     CrashLoopBackOff    8 (82s ago)     67m     10.104.19.31    4am-node28   <none>           <none>
 querynode-pod-failure-21648-milvus-datanode-6cb8cd5dcd-sfj5c      0/1     CrashLoopBackOff    8 (25s ago)     67m     10.104.16.187   4am-node21   <none>           <none>
 querynode-pod-failure-21648-milvus-mixcoord-559d964df5-mlc92      0/1     Running             4 (3s ago)      67m     10.104.32.252   4am-node39   <none>           <none>
 querynode-pod-failure-21648-milvus-proxy-547f9bc98f-n9x8m         1/1     Running             3 (66m ago)     67m     10.104.32.251   4am-node39   <none>           <none>
 querynode-pod-failure-21648-milvus-querynode-76479d66b9-t8xcc     1/1     Running             6 (42m ago)     67m     10.104.23.193   4am-node27   <none>           <none>
 querynode-pod-failure-21648-milvus-querynode-76479d66b9-tr9tf     1/1     Running             6 (42m ago)     67m     10.104.6.52     4am-node13   <none>           <none>
 querynode-pod-failure-21648-milvus-querynode-76479d66b9-xx9lc     1/1     Running             6 (42m ago)     67m     10.104.25.183   4am-node30   <none>           <none>
 querynode-pod-failure-21648-milvus-streamingnode-c676864cdrmjlk   0/1     Error               6 (5m25s ago)   67m     10.104.22.99    4am-node26   <none>           <none>
 querynode-pod-failure-21648-milvus-streamingnode-c676864cdxd54z   0/1     Error               6 (5m14s ago)   67m     10.104.9.58     4am-node14   <none>           <none>
 querynode-pod-failure-21648-minio-0                               1/1     Running             0               67m     10.104.15.20    4am-node20   <none>           <none>
 querynode-pod-failure-21648-minio-1                               1/1     Running             0               67m     10.104.21.72    4am-node24   <none>           <none>
 querynode-pod-failure-21648-minio-2                               1/1     Running             0               67m     10.104.30.47    4am-node38   <none>           <none>
 querynode-pod-failure-21648-minio-3                               1/1     Running             0               67m     10.104.17.53    4am-node23   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-0                     1/1     Running             0               67m     10.104.21.67    4am-node24   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-1                     1/1     Running             0               67m     10.104.17.42    4am-node23   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-2                     1/1     Running             0               67m     10.104.30.46    4am-node38   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-bookie-init-fvbtb            0/1     Completed           0               67m     10.104.13.20    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-broker-0                     1/1     Running             0               67m     10.104.13.22    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-broker-1                     1/1     Running             0               67m     10.104.14.129   4am-node18   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-proxy-0                      1/1     Running             0               67m     10.104.13.19    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-proxy-1                      1/1     Running             0               67m     10.104.14.128   4am-node18   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-pulsar-init-hvnxm            0/1     Completed           0               67m     10.104.13.18    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-recovery-0                   1/1     Running             0               67m     10.104.13.15    4am-node16   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-zookeeper-0                  1/1     Running             0               67m     10.104.15.17    4am-node20   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-zookeeper-1                  1/1     Running             0               67m     10.104.21.68    4am-node24   <none>           <none>
 querynode-pod-failure-21648-pulsarv3-zookeeper-2                  1/1     Running             0               67m     10.104.17.43    4am-node23   <none>           <none>
```

**Comment by congqixia** [comment]
Stack trace looks like the same issue resolved by #43056 
Did you enable storage v2 during this chaos test? @zhuwenxing

**Comment by zhuwenxing** [comment]
>Did you enable storage v2 

yes @congqixia

**Comment by congqixia** [comment]
Checked the commit. It does not include the patch, could please check whether this problem persist next run. thanks!
@zhuwenxing

**Comment by zhuwenxing** [comment]
still reproduced in master-20250703-f6b2a71c-amd64

failed job: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/21660/pipeline
log:

[artifacts-querynode-pod-failure-21660-server-logs.tar.gz](https://github.com/user-attachments/files/21035897/artifacts-querynode-pod-failure-21660-server-logs.tar.gz)

```
SIGSEGV: segmentation violation
PC=0x7fcc55273cae m=21 sigcode=1 addr=0x0
signal arrived during cgo execution

goroutine 517 gp=0xc002381180 m=21 mp=0xc002580008 [syscall]:
_ZN14milvus_storage19MakeArrowFileReaderERN5arrow2fs10FileSystemERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN7parquet16ReaderPropertiesE
	/workspace/source/cmake_build/thirdparty/milvus-storage/milvus-storage-src/cpp/src/common/arrow_util.cpp:37 pc=0x7fcc55273cae
_ZN14milvus_storage18FileRowGroupReader4initESt10shared_ptrIN5arrow2fs10FileSystemEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEElS1_INS2_6SchemaEEN7parquet16ReaderPropertiesE
	/workspace/source/cmake_build/thirdparty/milvus-storage/milvus-storage-src/cpp/src/format/parquet/file_reader.cpp:74 pc=0x7fcc552ee86e
runtime.cgocall(0x55266b0, 0xc0021a1668)
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.linux-amd64/src/runtime/cgocall.go:167 +0x4b fp=0xc0021a1640 sp=0xc0021a1608 pc=0x1f5d16b
github.com/milvus-io/milvus/internal/util/indexcgowrapper._Cfunc_CreateIndex(0xc000149b00, 0xc0016f0a80, 0x36c)
	_cgo_gotypes.go:306 +0x4f fp=0xc0021a1668 sp=0xc0021a1640 pc=0x4728c8f
github.com/milvus-io/milvus/internal/util/indexcgowrapper.CreateIndex.func1(...)
	/workspace/source/internal/util/indexcgowrapper/index.go:113
github.com/milvus-io/milvus/internal/util/indexcgowrapper.CreateIndex({0x68fbd00, 0xc001f4e690}, 0xc001c35760)
	/workspace/source/internal/util/indexcgowrapper/index.go:113 +0x3c5 fp=0xc0021a1808 sp=0xc0021a1668 pc=0x472a325
github.com/milvus-io/milvus/internal/datanode/index.(*indexBuildTask).Execute(0xc002246000, {0x68fbd00, 0xc001f4e690})
	/workspace/source/internal/datanode/index/task_index.go:310 +0x1db6 fp=0xc0021a1db8 sp=0xc0021a1808 pc=0x473d916
github.com/milvus-io/milvus/internal/datanode/index.Task.Execute-fm({0x68fbd00?, 0xc001f4e690?})
	<autogenerated>:1 +0x38 fp=0xc0021a1de0 sp=0xc0021a1db8 pc=0x474e2b8
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).processTask.func1(...)
	/workspace/source/internal/datanode/index/scheduler.go:236
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).processTask(0xc00201a4c0, {0x6929598, 0xc002246000}, {0xc001e80850?, 0x0?})
	/workspace/source/internal/datanode/index/scheduler.go:249 +0x350 fp=0xc0021a1f88 sp=0xc0021a1de0 pc=0x4736770
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).indexBuildLoop.func1({0x6929598?, 0xc002246000?})
	/workspace/source/internal/datanode/index/scheduler.go:272 +0x31 fp=0xc0021a1fc0 sp=0xc0021a1f88 pc=0x4736db1
github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).indexBuildLoop.gowrap2()
	/workspace/source/internal/datanode/index/scheduler.go:273 +0x28 fp=0xc0021a1fe0 sp=0xc0021a1fc0 pc=0x4736d48
runtime.goexit({})
	/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.linux-amd64/src/runtime/asm_amd64.s:1700 +0x1 fp=0xc0021a1fe8 sp=0xc0021a1fe0 pc=0x1f6a261
created by github.com/milvus-io/milvus/internal/datanode/index.(*TaskScheduler).indexBuildLoop in goroutine 363
	/workspace/source/internal/datanode/index/scheduler.go:271 +0xb5
```

same panic stack

```
 querynode-pod-failure-21660-milvus-datanode-8647cfdff-9r94t       0/1     Running            7 (2m39s ago)   35m     10.104.23.221   4am-node27   <none>           <none>
```


cluster: 4am
ns: chaos-testing
pods
```
 + kubectl get pods -o wide
 + grep querynode-pod-failure-21660
 querynode-pod-failure-21660-etcd-0                                1/1     Running            0               35m     10.104.16.114   4am-node21   <none>           <none>
 querynode-pod-failure-21660-etcd-1                                1/1     Running            0               35m     10.104.33.79    4am-node36   <none>           <none>
 querynode-pod-failure-21660-etcd-2                                1/1     Running            0               35m     10.104.20.242   4am-node22   <none>           <none>
 querynode-pod-failure-21660-milvus-datanode-8647cfdff-9r94t       0/1     Running            7 (2m39s ago)   35m     10.104.23.221   4am-node27   <none>           <none>
 querynode-pod-failure-21660-milvus-datanode-8647cfdff-ctzvt       1/1     Running            2 (35m ago)     35m     10.104.18.156   4am-node25   <none>           <none>
 querynode-pod-failure-21660-milvus-mixcoord-584d8dcf44-gsqfl      1/1     Running            2 (35m ago)     35m     10.104.18.157   4am-node25   <none>           <none>
 querynode-pod-failure-21660-milvus-proxy-7f56d4798d-6mkzf         1/1     Running            2 (35m ago)     35m     10.104.18.155   4am-node25   <none>           <none>
 querynode-pod-failure-21660-milvus-querynode-c7dd8b5db-78sst      1/1     Running            6 (9m14s ago)   35m     10.104.32.3     4am-node39   <none>           <none>
 querynode-pod-failure-21660-milvus-querynode-c7dd8b5db-fk2l7      1/1     Running            6 (9m14s ago)   35m     10.104.23.220   4am-node27   <none>           <none>
 querynode-pod-failure-21660-milvus-querynode-c7dd8b5db-jr2w8      1/1     Running            5 (9m14s ago)   35m     10.104.25.147   4am-node30   <none>           <none>
 querynode-pod-failure-21660-milvus-streamingnode-67f898b97h5tlh   1/1     Running            3 (34m ago)     35m     10.104.32.2     4am-node39   <none>           <none>
 querynode-pod-failure-21660-milvus-streamingnode-67f898b97w95gk   1/1     Running            2 (35m ago)     35m     10.104.18.158   4am-node25   <none>           <none>
 querynode-pod-failure-21660-minio-0                               1/1     Running            1 (8m19s ago)   35m     10.104.16.117   4am-node21   <none>           <none>
 querynode-pod-failure-21660-minio-1                               1/1     Running            1 (7m31s ago)   35m     10.104.20.241   4am-node22   <none>           <none>
 querynode-pod-failure-21660-minio-2                               1/1     Running            1 (7m29s ago)   35m     10.104.33.83    4am-node36   <none>           <none>
 querynode-pod-failure-21660-minio-3                               1/1     Running            1 (8m ago)      35m     10.104.21.18    4am-node24   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-bookie-0                     1/1     Running            0               35m     10.104.33.82    4am-node36   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-bookie-1                     1/1     Running            0               35m     10.104.20.238   4am-node22   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-bookie-2                     1/1     Running            0               35m     10.104.16.119   4am-node21   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-bookie-init-jgjsr            0/1     Completed          0               35m     10.104.20.228   4am-node22   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-broker-0                     1/1     Running            0               35m     10.104.33.73    4am-node36   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-broker-1                     1/1     Running            0               35m     10.104.16.110   4am-node21   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-proxy-0                      1/1     Running            0               35m     10.104.33.68    4am-node36   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-proxy-1                      1/1     Running            0               35m     10.104.20.229   4am-node22   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-pulsar-init-4lktp            0/1     Completed          0               35m     10.104.33.67    4am-node36   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-recovery-0                   1/1     Running            0               35m     10.104.33.70    4am-node36   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-zookeeper-0                  1/1     Running            0               35m     10.104.33.77    4am-node36   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-zookeeper-1                  1/1     Running            0               35m     10.104.20.234   4am-node22   <none>           <none>
 querynode-pod-failure-21660-pulsarv3-zookeeper-2                  1/1     Running            0               35m     10.104.16.115   4am-node21   <none>           <none>
```

**Comment by congqixia** [comment]
@zhuwenxing patch has been merged, could you please verify?

**Comment by zhuwenxing** [comment]
verified anf fixed in master-20250708-ed9aa1d4-amd64
