### ISSUE TITLE
Batch inserting binary data is too slow

### ISSUE THREAD

**Issue by shiyu22** [milvus-io/milvus#7181]
#### Steps/Code to reproduce:
1. create a collection with the binary vector
2. batch insert binary vectors and return the cost

#### Expected result:
Insert 100,000 data in seconds and the insertion time for insert data is linear.

#### Actual results:
It took 900 seconds to insert 100,000 vectors with 2048 dimension and I also tested different amounts of data, but when the batch inserted  200,000 Milvus hangs.
1000 -> 200ms
10000 -> 5s
50000 -> 200s
100000 -> 900s

#### Environment:
- Milvus v2.0.0-RC4
- Standalone & Cluster
- Pymilvus v2.0.0rc4
- Ubuntu

#### Additional context:
I test it both with standalone and Cluster and they will appear.

**Comment by congqixia** [comment]
@shiyu22 I was wondering that if you could provide that test scripts / code. Wanna make clear you manually separate data into batches or let the pymilvus do it for you.

**Comment by shiyu22** [comment]
1. First create collection with binary type:
```python
def create_binary_collection(collection_name):
    if not utility.has_collection(collection_name):
        field1 = FieldSchema(name="id", dtype=DataType.INT64, descrition="int64", is_primary=True,
                                auto_id=Ture)
        field2 = FieldSchema(name="embedding", dtype=DataType.BINARY_VECTOR, descrition="binary vector",
                                dim=2048, is_primary=False)
        schema = CollectionSchema(fields=[field1, field2], description="collection description")
        collection = Collection(name=collection_name, schema=schema)
        return collection
```

2. Then I will load the data with `numpy` format:
```python
def load_hex_data(filename):
    data = np.load(filename)
    vectors = []
    for d in data:
        vectors.append(bytes.fromhex(d))
    return vectors
```
There are nearly 200,000 2048 dimensions of data in the file.

2. Finally batch insert in Milvus with the parameter `BATH_NUM`, which can be adjusted like 10000, 50000, 200000 etc. 
```python
def hex_to_milvus(collection_name, client):
    vectors = load_hex_data(filename)
    ids_lens = 0
    BATH_NUM = 10000
    collection = create_binary_collection("test_binary")
    while ids_lens<len(vectors) :
        time_add_start = time.time()
        ids = collection.insert([vectors[ids_lens:ids_lens+BATH_NUM]])
        print("insert milvus time: ", time.time() - time_add_start)
        ids_lens += BATH_NUM
```

**Comment by congqixia** [comment]
@shiyu22 thanks! working on it
/unassign @shiyu22 
/assign

**Comment by congqixia** [comment]
@shiyu22 just checked with latest version on master branch. The average insert time for each 10000 vector batch is about 5 seconds. Look like it's solved in the RC-5 release. Would you please verify this after the RC-5 released?
/assign @shiyu22 
/unassign

**Comment by shiyu22** [comment]
When will RC-5 be released? And does it resolve in both standalone and clusters?

**Comment by congqixia** [comment]
> When will RC-5 be released? And does it resolve in both standalone and clusters?

@shiyu22 it should be today. Due to a blocking issue, rc-5 shall be available next Monday.

**Comment by shiyu22** [comment]
I can still reproduce this issue on rc5 and a single batch insert of 200,000 has not been returning and the datanode does not update the log, I am deploying Milvus cluster on k8s, refer to https://mithub.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml

**Comment by congqixia** [comment]
> I can still reproduce this issue on rc5 and a single batch insert of 200,000 has not been returning and the datanode does not update the log, I am deploying Milvus cluster on k8s, refer to https://mithub.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml

It's an known issue that Insert large data set in one operation may fail due to network problem. We plan to devide the insert request into smaller ones to solve this issue.

**Comment by congqixia** [comment]
> I can still reproduce this issue on rc5 and a single batch insert of 200,000 has not been returning and the datanode does not update the log, I am deploying Milvus cluster on k8s, refer to https://mithub.com/milvus-io/milvus-helm/blob/master/charts/milvus/values.yaml

It looks like I misunderstood the original issue. The time consumption of each insert operation(which I thought was the whole size of data) does not scale up linear with the batch size. I'll try to reproduce that.

**Comment by shiyu22** [comment]
Is this only a problem with binary data, or is it also for float data?
